import {test,expect,type Page} from '@playwright/test';
import type {Report} from '../../src/features/reports/contracts';
const data=(kind:string,rows:Report['rows']=[],metrics:Report['metrics']={}):Report=>({reportKind:kind as Report['reportKind'],metrics,rows,totalRows:rows.length,nextCursor:null,appliedFilters:{startDate:'2026-09-01',endDate:'2026-09-26',timezone:'Asia/Karachi',branchIds:[],allBranches:true},dataAsOf:'2026-09-26T12:00:00Z'});
async function intercept(page:Page){await page.route('**/api/reports/read',async route=>{const f=route.request().postDataJSON().filters;await route.fulfill({json:{data:data(f.reportKind,f.reportKind==='overview'?[{date:'2026-09-26',recordedSalesPaisa:'160000',eligibleSpendPaisa:'120000',purchases:4,reversedPurchases:1}]:[],f.reportKind==='overview'?{recordedSalesPaisa:'160000',recordedPurchases:4,averageBillPaisa:'40000'}:{manualTasksOpened:2,manualTasksStaffMarkedSent:1})}});});}
test('only active tab is fetched; duplicate refresh is disabled and failed refresh clears old values',async({page})=>{
 const calls:string[]=[];let fail=false;
 await page.route('**/api/reports/read',async route=>{const f=route.request().postDataJSON().filters;calls.push(f.reportKind);await new Promise(r=>setTimeout(r,150));await route.fulfill(fail?{status:503,json:{error:{message:'The report took too long. Retry or narrow the date range.'}}}:{json:{data:data(f.reportKind,[{date:'2026-09-26',recordedSalesPaisa:'160000',eligibleSpendPaisa:'120000',purchases:4,reversedPurchases:1}],{recordedSalesPaisa:'160000'})}});});
 await page.goto('/ui-fixtures/phase7');await expect(page.getByText('1,600.00',{exact:true}).first()).toBeVisible();expect(calls).toEqual(['overview']);
 fail=true;await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('button',{name:'Refresh',exact:true})).toBeDisabled();
 await expect(page.locator('.reports-view').getByRole('alert')).toContainText('took too long');await expect(page.getByText('1,600.00',{exact:true})).toHaveCount(0);expect(calls).toEqual(['overview','overview']);
 fail=false;await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByText('1,600.00',{exact:true}).first()).toBeVisible();
 await page.getByRole('tab',{name:'Campaigns',exact:true}).click();await expect(page.getByRole('tab',{name:'Campaigns'})).toHaveAttribute('aria-selected','true');await expect(page.getByText('Updated ',{exact:false})).toBeVisible();expect(calls.at(-1)).toBe('campaigns');
});
test('custom date validation blocks 91 days; pagination and branch filters are sent to the server',async({page})=>{
 const payloads:Record<string,unknown>[]=[];await page.route('**/api/reports/read',async route=>{const f=route.request().postDataJSON().filters;payloads.push(f);await route.fulfill({json:{data:{...data(f.reportKind),totalRows:50,nextCursor:f.cursor==='0'?'25':null}}});});
 await page.goto('/ui-fixtures/phase7');await expect(page.getByRole('button',{name:'Next',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('Page 2',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Next',exact:true})).toBeDisabled();expect(payloads.at(-1)?.cursor).toBe('25');
 await page.getByLabel('Date range',{exact:true}).selectOption('custom');await page.getByLabel('Start date',{exact:true}).fill('2026-01-01');await page.getByLabel('End date',{exact:true}).fill('2026-04-01');await expect(page.locator('.reports-view').getByRole('alert')).toContainText('1–90');const before=payloads.length;await page.getByRole('button',{name:'Refresh',exact:true}).click();expect(payloads.length).toBe(before);
 await page.getByLabel('End date',{exact:true}).fill('2026-03-31');await expect(page.locator('.reports-view').getByRole('alert')).toHaveCount(0);await page.getByLabel('Branch',{exact:true}).selectOption('b7000000-0000-4000-8000-000000000002');await expect.poll(()=>payloads.at(-1)?.branchIds).toEqual(['b7000000-0000-4000-8000-000000000002']);
});
test('CSV confirmation excludes PII by default and retries retain the export idempotency key',async({page})=>{
 await intercept(page);const keys:string[]=[];await page.route('**/api/reports/export',async route=>{const v=route.request().postDataJSON();keys.push(v.idempotencyKey);expect(v.columns).not.toContain('name');expect(v.columns).not.toContain('phone');expect(v.filters.preset).toBe('custom');await route.fulfill(keys.length===1?{status:503,json:{error:{message:'Export unavailable. Retry.'}}}:{json:{data:{exportRequestId:'b7000000-0000-4000-8000-000000000008',status:'pending'}}});});
 await page.goto('/ui-fixtures/phase7');await page.getByRole('tab',{name:'Customers',exact:true}).click();await expect(page.getByText('No activity matches',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Export CSV',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Export selected report?'})).toBeVisible();await expect(page.getByRole('checkbox',{name:'Name',exact:true})).not.toBeChecked();expect(keys).toHaveLength(0);
 await page.getByRole('button',{name:'Create private export',exact:true}).click();await expect(page.locator('.reports-view').getByRole('alert')).toContainText('Export unavailable');await page.getByRole('button',{name:'Create private export',exact:true}).click();await expect(page.getByText('Export pending.',{exact:true})).toBeVisible();expect(keys[0]).toBe(keys[1]);await expect(page.getByRole('link',{name:'Download CSV'})).toHaveCount(0);
});
test('all report tabs fit 360px and charts have table alternatives; managers have no export controls without a grant',async({page})=>{
 await intercept(page);await page.goto('/ui-fixtures/phase7');await expect(page.getByRole('table')).toBeVisible();await expect(page.getByText('Updated ',{exact:false})).toBeVisible();
 await expect(page.locator('.recharts-bar-rectangle')).toBeVisible();await page.screenshot({path:test.info().outputPath('phase7-overview.png'),fullPage:true});
 for(const name of ['Customers','Rewards','Referrals','Double slots','Campaigns','Staff']){await page.getByRole('tab',{name,exact:true}).click();await expect(page.getByText('No activity matches',{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name).toBe(true);}
 await page.getByRole('tab',{name:'Overview',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Customers',exact:true})).toBeFocused();
 await page.goto('/ui-fixtures/phase7?role=manager');await expect(page.getByText('Updated ',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Export CSV'})).toHaveCount(0);await expect(page.getByRole('button',{name:'Export shared contacts'})).toHaveCount(0);await expect(page.getByRole('option',{name:'All assigned branches'})).toHaveCount(1);
});
test('private report and export endpoints safely reject missing identity and never cache responses',async({request})=>{
 for(const path of ['/api/reports/read','/api/reports/export','/api/reports/export-status']){const response=await request.post(path,{data:{}});expect([401,403,503]).toContain(response.status());expect(response.headers()['cache-control']).toContain('private, no-store');}
 const response=await request.get('/api/reports/download?businessId=test&exportRequestId=test');expect(response.status()).toBe(401);expect(response.headers()['cache-control']).toContain('private, no-store');
});
