import {test,expect} from '@playwright/test';
test('owner evidence stays pending and retries keep their key; billing fits mobile',async({page})=>{
 const keys:string[]=[];await page.route('**/api/platform/evidence',async r=>{keys.push(r.request().postDataJSON().idempotencyKey);await r.fulfill({status:503,json:{error:{message:'Payment review unavailable. Retry.'}}});});
 await page.goto('/ui-fixtures/phase8');await expect(page.getByText('Payment instructions need operator configuration.',{exact:false})).toBeVisible();await page.getByLabel('Claimed amount (Rs)').fill('5500.50');await page.getByLabel('Transfer reference').fill('TEST bank claim');await page.getByRole('button',{name:'Submit for review'}).click();await expect(page.locator('main').getByRole('alert')).toContainText('unavailable');await page.getByRole('button',{name:'Submit for review'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await expect(page.getByText('An uploaded image does not activate your plan.',{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('phase8-billing.png'),fullPage:true});
});
test('billing review requires reconciliation and confirmation; server MFA denial is visible',async({page})=>{
 let calls=0;await page.route('**/api/platform/reconcile',async r=>{calls++;expect(r.request().postDataJSON().input.reconciled).toBe(true);await r.fulfill({status:403,json:{error:{message:'Recent MFA is required.'}}});});page.on('dialog',d=>d.accept());await page.goto('/ui-fixtures/phase8?form=admin');await page.getByRole('button',{name:'View invoice'}).click();await page.getByLabel('Verified amount (Rs)').fill('5500.50');await page.getByLabel('Canonical bank/provider ID').fill('test-bank');await page.getByLabel('External reference').fill('TEST reconciled ref');await page.getByRole('button',{name:'Review payment'}).click();await expect(page.locator('main').getByRole('alert')).toBeVisible();expect(calls).toBe(0);await page.getByRole('checkbox',{name:'I reconciled the actual bank/provider record'}).check();await page.getByRole('button',{name:'Review payment'}).click();await expect(page.locator('main').getByRole('alert')).toContainText('Recent MFA');expect(calls).toBe(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath('phase8-admin.png'),fullPage:true});
});
test('editing fractional plan price preserves paisa and publishing asks confirmation',async({page})=>{
 let sent:Record<string,unknown>|undefined;await page.route('**/api/platform/save-plan',async r=>{sent=r.request().postDataJSON();await r.fulfill({status:403,json:{error:{message:'Recent MFA is required.'}}});});await page.goto('/ui-fixtures/phase8?form=plans');await page.getByRole('button',{name:'View record'}).click();await expect(page.getByLabel('Price (Rs)')).toHaveValue('5500.50');await page.getByRole('checkbox',{name:'Publish immutable version'}).check();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Save plan version'}).click();expect(sent).toBeUndefined();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Save plan version'}).click();await expect.poll(()=>sent).toBeTruthy();expect((sent?.input as Record<string,unknown>).pricePaisa).toBe('550050');
});
test('privacy owner blocker is honest; retained categories and requester downloads are visible',async({page})=>{
 await page.route('**/api/platform/privacy-request',r=>r.fulfill({json:{data:{status:'blocked',errorCode:'active_business_owner'}}}));await page.route('**/api/platform/privacy-status',r=>r.fulfill({json:{data:{retentionConfigured:false,financialPolicy:null,backupCoverage:null,requests:[{id:'b8000000-0000-4000-8000-000000000008',kind:'delete_account',status:'blocked',membershipId:null,requestedAt:'2026-09-27T05:00:00Z',completedAt:null,errorCode:'active_business_owner',retainedCategories:['Financial ledger','Minimal audit'],exportRequestId:null,expiresAt:null,parts:[]}]}}}));page.on('dialog',d=>d.accept());await page.goto('/ui-fixtures/phase8?form=privacy');await page.getByRole('button',{name:'Request account deletion'}).click();await expect(page.getByRole('status')).toContainText('Deletion blocked');await expect(page.getByText('Retained categories:',{exact:false})).toContainText('Financial ledger');await expect(page.getByRole('link',{name:'Download manifest'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('private billing/privacy endpoints deny missing identity and never cache',async({request})=>{
 for(const op of ['billing','evidence','reconcile','correct','admin-read','privacy-request']){const r=await request.post(`/api/platform/${op}`,{data:{}});expect([401,403,503]).toContain(r.status());expect(r.headers()['cache-control']).toContain('private, no-store');}for(const path of ['/api/privacy/download?artifactId=test','/api/platform/proof?assetId=test','/api/platform/invoice?businessId=test&invoiceId=test']){const r=await request.get(path);expect([401,403,503]).toContain(r.status());expect(r.headers()['cache-control']).toContain('private, no-store');}
});
