'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {formatPaisa} from '@/lib/formatting';
import type {AdminData} from './contracts';
import {plan,reconciliation} from './contracts';
import {formPaisa,platformRequest,platformError} from './client';

const titles:Record<string,string>={overview:'Administration',businesses:'Tenants',plans:'Plans',billing:'Billing review',jobs:'Jobs and incidents',audit:'Audit',privacy:'Privacy requests'};
const columns:Record<string,string[]>={businesses:['name','slug','status','subscriptionStatus','ownerId','branches','createdAt'],plans:['code','name','version','status','pricePaisa','billingPeriod','branchLimit','staffLimit','memberLimit','monthlyCampaignLimit','trialDays'],billing:['business','reference','amountPaisa','periodStart','periodEnd','dueAt','status'],jobs:['eventType','state','queueState','attempts','nextAttempt','createdAt'],audit:['occurredAt','actor','action','businessId','target','targetId','reason','correlationId','supportGrantId'],privacy:['kind','status','subjectId','requestedAt','completedAt','errorCode']};
const label=(v:string)=>v.endsWith('Paisa')?`${v.slice(0,-5).replace(/([A-Z])/gu,' $1')} (Rs)`:v.replace(/([A-Z])/gu,' $1').replace(/^./u,c=>c.toUpperCase());
const show=(key:string,value:unknown)=>value==null?'N/A':key.endsWith('Paisa')?formatPaisa(String(value)):String(value).replaceAll('_',' ');
type Selected=Record<string,unknown>;
type Payment={id:string;event:string;corrected:boolean;amountPaisa:string};
type Submission={id:string;status:string;claimedAmountPaisa:string;method:string;reference:string;proofAssetId:string|null;reviewNote:string|null};
export function Admin({kind,initial,businessId,invoiceId}:{kind:string;initial:AdminData;businessId?:string;invoiceId?:string}){
 const [data,setData]=useState(initial),[selected,setSelected]=useState<Selected|null>(()=>initial.rows?.find(r=>r.id===(invoiceId??businessId))??null),[pending,setPending]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[page,setPage]=useState(1),[status,setStatus]=useState(''),[business,setBusiness]=useState(businessId??''),[grant,setGrant]=useState<{grantId:string;expiresAt:string}|null>(null),[support,setSupport]=useState<Selected|null>(null),[extra,setExtra]=useState<Record<string,string>>({});
 const key=useRef('');
 const filters=()=>({page,pageSize:25,...(status?{status}:{}),...(business?{businessId:business}:{}),...(invoiceId?{invoiceId}:{}),...Object.fromEntries(Object.entries(extra).filter(([,v])=>v))});
 const load=async(nextPage=page)=>{const next=await platformRequest<AdminData>(kind==='privacy'?'privacy-queue':'admin-read',kind==='privacy'?{page:nextPage}:{kind,filters:{...filters(),page:nextPage}});setData(next);setPage(nextPage);if(selected)setSelected(next.rows?.find(r=>r.id===selected.id)??null);};
 const act=async(action:()=>Promise<void>)=>{setPending(true);setError('');setMessage('');try{await action();}catch(e){setError(platformError(e));}finally{setPending(false);}};
 const submit=(event:React.FormEvent<HTMLFormElement>,action:(form:FormData)=>Promise<void>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(()=>action(form));};
 const newKey=()=>{if(!key.current)key.current=crypto.randomUUID();return key.current;};
 return <><nav className="actions" aria-label="Administration">{Object.keys(titles).map(k=><Link key={k} href={k==='overview'?'/admin':`/admin/${k==='businesses'?'businesses':k}`} aria-current={kind===k?'page':undefined}>{titles[k]}</Link>)}<Link href="/workspace">Workspace</Link></nav><h1>{titles[kind]}</h1><p>MFA and current platform permissions are required. Sensitive actions also require a sign-in or MFA challenge within 15 minutes.</p>
  {kind==='overview'?<><section className="screen-panel"><h2>Operational overview</h2><dl className="platform-usage">{Object.entries(data.counts??{}).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{v??'Unknown'}</dd></div>)}</dl></section><section className="screen-panel"><h2>Independent checks</h2>{['worker_heartbeat','db_readiness','backup','restore_rehearsal','ledger_reconciliation'].map(name=>{const c=data.checks?.find(c=>c.name===name);return <p key={name}>{label(name.replaceAll('_',' '))}: <strong>{c?.status??'Unknown'}</strong>{c&&` · ${new Date(c.checkedAt).toLocaleString('en-PK')}`}</p>;})}<p>Provider acceptance and device delivery are separate. Missing backup evidence is Unknown.</p></section></>:<>
   <form className="actions" onSubmit={e=>{e.preventDefault();void act(()=>load(1));}}>{!['privacy','plans'].includes(kind)&&<label className="field">Business ID<input value={business} onChange={e=>setBusiness(e.target.value)} placeholder="All permitted tenants"/></label>}{!['plans','audit'].includes(kind)&&<label className="field">Status<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="All statuses"/></label>}{(kind==='businesses'?['planVersionId']:kind==='audit'?['actorId','action','supportGrantId','from','until']:kind==='jobs'?['eventType','from','until']:[]).map(k=><label className="field" key={k}>{label(k)}<input value={extra[k]??''} placeholder={['from','until'].includes(k)?'ISO timestamp with timezone':''} onChange={e=>setExtra({...extra,[k]:e.target.value})}/></label>)}<Button disabled={pending}>Apply filters</Button></form>
   {data.rows?.length?<div className="table-scroll"><table className="platform-table"><thead><tr>{columns[kind]?.map(c=><th key={c}>{label(c)}</th>)}<th>Details</th></tr></thead><tbody>{data.rows.map(r=><tr key={String(r.id)}>{columns[kind]?.map(c=><td key={c}>{show(c,r[c])}</td>)}<td>{kind==='audit'?<span>Append-only</span>:<Button variant="secondary" disabled={pending} onClick={()=>{setSelected(r);key.current='';setSupport(null);}}>View {kind==='billing'?'invoice':'record'}</Button>}</td></tr>)}</tbody></table></div>:<p>No records match these filters.</p>}
   <div className="actions"><Button variant="secondary" disabled={pending||page===1} onClick={()=>void act(()=>load(page-1))}>Previous</Button><span>Page {page} · {data.total??0} records</span><Button variant="secondary" disabled={pending||page*25>=(data.total??0)} onClick={()=>void act(()=>load(page+1))}>Next</Button></div>
  </>}
  {kind==='overview'&&data.capabilities?.support&&<section className="screen-panel"><h2>Operator configuration</h2><p>Record actual payment accounts, canonical provider IDs, approved retention and purchased backup coverage. These values appear in billing/privacy screens.</p><dl>{Object.entries(data.settings??{}).map(([k,v])=><div key={k}><dt>{label(k.replaceAll('_',' '))}</dt><dd>{Array.isArray(v)?v.join(', '):String(v)}</dd></div>)}</dl><form onSubmit={e=>submit(e,async f=>{const k=String(f.get('key')),raw=String(f.get('value'));const value=k==='canonical_providers'?raw.split(',').map(v=>v.trim()):k.endsWith('_days')||k.endsWith('_hours')?Number(raw):raw;if(!window.confirm('Update this platform setting with the recorded audit reason?'))return;await platformRequest('setting',{key:k,value,reason:f.get('reason')});await load();setMessage('Operator configuration audited.');})}><label className="field">Setting<select name="key">{['billing_instructions','canonical_providers','financial_retention_policy','backup_coverage','grace_days','notification_retention_days','log_retention_days','referral_visit_retention_days','device_retention_days','temporary_retention_hours'].map(k=><option key={k} value={k}>{label(k.replaceAll('_',' '))}</option>)}</select></label><label className="field">Value (providers comma-separated; numeric policy days/hours)<textarea name="value" required maxLength={4000}/></label><label className="field">Configuration reason<textarea name="reason" required minLength={10} maxLength={500}/></label><Button disabled={pending}>Save operator configuration</Button></form></section>}
  {kind==='jobs'&&<section className="screen-panel"><h2>Independent health checks</h2>{(data.checks??[]).map(c=><p key={c.name}>{label(c.name.replaceAll('_',' '))}: {c.status} · {c.checkedAt}</p>)}{!data.checks?.length&&<p>Health evidence is Unknown.</p>}</section>}
  {selected&&kind==='billing'&&<section className="screen-panel"><h2>{String(selected.reference)} · {formatPaisa(String(selected.amountPaisa))}</h2><p>Covered period {String(selected.periodStart)} – {String(selected.periodEnd)} · {String(selected.status)}</p>
   {(selected.submissions as Submission[]).map(s=><p key={s.id}>{s.id} · {formatPaisa(s.claimedAmountPaisa)} · {s.method.replaceAll('_',' ')} · {s.reference} · {s.status}{s.reviewNote&&` · ${s.reviewNote}`}{s.proofAssetId&&<> · <a href={`/api/platform/proof?assetId=${s.proofAssetId}`} target="_blank" rel="noreferrer">Review private proof</a></>}</p>)}
   {['issued','overdue'].includes(String(selected.status))&&<form onChange={()=>{key.current='';}} onSubmit={e=>submit(e,async f=>{const decision=String(f.get('decision'));if(!window.confirm(decision==='confirm'?'Confirm actual reconciliation for this exact invoice, amount and provider reference? This affects subscription access.':'Reject this payment evidence with the recorded reason?'))return;
    const input=reconciliation.parse({invoiceId:selected.id,idempotencyKey:newKey(),input:{submissionId:String(f.get('submissionId'))||undefined,decision,verifiedAmountPaisa:decision==='confirm'?formPaisa(f.get('amount')):undefined,method:decision==='confirm'?f.get('method'):undefined,provider:decision==='confirm'?f.get('provider'):undefined,reference:decision==='confirm'?f.get('reference'):undefined,reason:String(f.get('reason'))||undefined,reconciled:f.get('reconciled')==='on'}});await platformRequest('reconcile',input);key.current='';setMessage(decision==='confirm'?'Verified payment recorded.':'Evidence rejected.');await load();})}>
    <label className="field">Submission<select name="submissionId"><option value="">Operator reconciliation without uploaded evidence</option>{(selected.submissions as Submission[]).filter(s=>s.status==='pending_review').map(s=><option key={s.id} value={s.id}>{s.id}</option>)}</select></label><label className="field">Decision<select name="decision"><option value="confirm">Confirm</option><option value="reject">Reject</option></select></label><label className="field">Verified amount (Rs)<input name="amount" inputMode="decimal"/></label><label className="field">Method<select name="method"><option value="bank_transfer">Bank transfer</option><option value="merchant_wallet">Merchant wallet</option></select></label><label className="field">Canonical bank/provider ID<input name="provider" maxLength={80}/></label><label className="field">External reference<input name="reference" maxLength={200}/></label><label className="field">Review reason (required on rejection)<textarea name="reason" maxLength={500}/></label><label><input type="checkbox" name="reconciled"/> I reconciled the actual bank/provider record</label><p>Proof alone is insufficient. Mismatched amounts and reused references are blocked.</p><Button disabled={pending}>Review payment</Button>
   </form>}
   {(selected.payments as Payment[]).filter(p=>p.event==='confirmed'&&!p.corrected).map(p=><form key={p.id} onSubmit={e=>submit(e,async f=>{if(!window.confirm('Append one correction for this verified payment? The invoice reopens; other valid paid intervals and customer balances remain.'))return;await platformRequest('correct',{paymentEventId:p.id,reason:f.get('reason'),idempotencyKey:newKey()});key.current='';await load();setMessage('Compensating correction recorded.');})}><p>Confirmed event {p.id} · {formatPaisa(p.amountPaisa)}</p><label className="field">Correction reason<textarea name="reason" required minLength={10} maxLength={500} onChange={()=>{key.current='';}}/></label><Button variant="secondary" disabled={pending}>Correct verified payment</Button></form>)}
  </section>}
  {kind==='plans'&&<section className="screen-panel"><h2>{selected?.status==='draft'?'Edit plan draft':'Create plan version'}</h2><p>Included: referrals, double slots, reporting and manual WhatsApp. Publishing preserves historical prices and limits.</p><form key={String(selected?.id??'new')} onSubmit={e=>submit(e,async f=>{const publish=f.get('publish')==='on';const input=plan.parse({publish,input:{...(selected?.status==='draft'?{id:selected.id}:{}),code:f.get('code'),name:f.get('name'),active:f.get('active')==='on',pricePaisa:formPaisa(f.get('price')),billingPeriod:f.get('interval'),branchLimit:Number(f.get('branches')),staffLimit:Number(f.get('staff')),memberLimit:String(f.get('members'))?Number(f.get('members')):null,monthlyCampaignLimit:String(f.get('campaigns'))?Number(f.get('campaigns')):null,trialDays:Number(f.get('trial'))}});if(publish&&!window.confirm('Publish this immutable plan version for new subscriptions and explicit plan changes?'))return;await platformRequest('save-plan',input);setSelected(null);await load();setMessage(publish?'Plan version published.':'Draft saved.');})}>
   <label className="field">Plan code<input name="code" required pattern="[a-z0-9-]{2,50}" defaultValue={String(selected?.code??'')}/></label><label className="field">Plan name<input name="name" required minLength={2} maxLength={80} defaultValue={String(selected?.name??'')}/></label><label className="field">Price (Rs)<input name="price" inputMode="decimal" required defaultValue={selected?`${BigInt(String(selected.pricePaisa))/100n}.${(BigInt(String(selected.pricePaisa))%100n).toString().padStart(2,'0')}`:''}/></label><label className="field">Billing interval<select name="interval" defaultValue={String(selected?.billingPeriod??'monthly')}><option value="monthly">Monthly</option><option value="annual">Annual</option></select></label>
   {(['branches','staff','members','campaigns','trial'] as const).map(k=><label className="field" key={k}>{k==='trial'?'Trial days':`${label(k)} limit`}{['members','campaigns'].includes(k)&&' (blank = unlimited by plan)'}<input name={k} type="number" min={k==='trial'?0:1} max={k==='trial'?30:2147483647} required={!['members','campaigns'].includes(k)} defaultValue={String(selected?.[({branches:'branchLimit',staff:'staffLimit',members:'memberLimit',campaigns:'monthlyCampaignLimit',trial:'trialDays'} as const)[k]]??(k==='trial'?'14':''))}/></label>)}<label><input type="checkbox" name="active" defaultChecked={selected?.active!==false}/> Active</label><label><input type="checkbox" name="publish"/> Publish immutable version</label><Button disabled={pending}>Save plan version</Button>
  </form></section>}
  {selected&&kind==='businesses'&&<section className="screen-panel"><h2>{String(selected.name)}</h2><p>Owner {String(selected.ownerId)} · Subscription {String(selected.subscriptionStatus)}</p><p>Suspension preserves customer balances/history, existing benefit fulfillment and reversals. New enrollment, earning and marketing stop immediately.</p><form onSubmit={e=>submit(e,async f=>{if(!window.confirm(`Apply ${String(f.get('action'))} to this tenant with the recorded reason?`))return;await platformRequest('tenant-action',{businessId:selected.id,action:f.get('action'),reason:f.get('reason')});await load();setMessage('Tenant action audited.');})}><label className="field">Action<select name="action"><option value="suspend">Suspend subscription</option><option value="reinstate">Reinstate subject to paid coverage</option><option value="pause">Pause publishing</option><option value="resume">Resume publishing</option></select></label><label className="field">Reason<textarea name="reason" required minLength={10} maxLength={500}/></label><Button disabled={pending}>Apply tenant action</Button></form>
   <h3>Change permitted plan</h3><p>Requires a current paid invoice with matching verified price and billing interval. Existing future invoices must agree. Existing records stay intact; lower limits block additions. Price/interval changes require a separately agreed renewal and cannot rewrite paid invoices.</p><form onSubmit={e=>submit(e,async f=>{if(!window.confirm('Change this tenant to the published version against the verified paid interval? Balances and historical invoices remain.'))return;await platformRequest('change-plan',{businessId:selected.id,planVersionId:f.get('planVersionId'),invoiceId:f.get('invoiceId'),reason:f.get('reason')});await load();setMessage('Permitted plan change audited.');})}><label className="field">Published plan version ID<input name="planVersionId" required/></label><label className="field">Current verified invoice ID<input name="invoiceId" required/></label><label className="field">Plan change reason<textarea name="reason" required minLength={10} maxLength={500}/></label><Button disabled={pending}>Change verified plan</Button></form>
   <h3>Audited support access</h3><form onSubmit={e=>submit(e,async f=>{const result=await platformRequest<{grantId:string;expiresAt:string}>('support-start',{businessId:selected.id,reason:f.get('reason'),scope:f.get('scope'),minutes:Number(f.get('minutes'))});setGrant(result);setSupport(null);})}><label className="field">Support reason<textarea name="reason" required minLength={10} maxLength={500}/></label><label className="field">Scope<select name="scope"><option value="configuration">Configuration</option><option value="transaction_support">Transaction support</option></select></label><label className="field">Duration<select name="minutes"><option>15</option><option>30</option><option>60</option></select></label><Button disabled={pending}>Start support session</Button></form>
   {grant&&<><p>Support expires {new Date(grant.expiresAt).toLocaleString('en-PK')}. No impersonation or contact export.</p><Button disabled={pending} onClick={()=>void act(async()=>setSupport(await platformRequest('support-read',{grantId:grant.grantId})))}>Read authorized support data</Button><Button variant="secondary" disabled={pending} onClick={()=>void act(async()=>{await platformRequest('support-end',{grantId:grant.grantId});setGrant(null);setSupport(null);})}>End support session</Button>{support&&<div><p>Scoped business: {String(support.businessId)}</p>{Boolean(support.programme)&&<p>Programme: {String((support.programme as Selected).name)} · {String((support.programme as Selected).status)}</p>}{((support.branches??support.purchases??[]) as Selected[]).map(r=><p key={String(r.id)}>{String(r.name??r.id)} · {String(r.status)}{Boolean(r.recordedBillPaisa)&&` · ${formatPaisa(String(r.recordedBillPaisa))}`}</p>)}</div>}</>}
  </section>}
  {selected&&['jobs','privacy'].includes(kind)&&<section className="screen-panel"><h2>Controlled recovery · {String(selected.id)}</h2><p>{kind==='jobs'?'Provider-unknown sends cannot be retried blindly. Retry is limited to still-valid database/artifact workflows.':'Failed deletion may have already removed identity data. Retry continues the recorded request after ownership blockers are resolved.'}</p><form onSubmit={e=>submit(e,async f=>{if(!window.confirm('Execute this scoped recovery with the recorded reason?'))return;await platformRequest(kind==='jobs'?'job-action':'privacy-retry',kind==='jobs'?{eventId:selected.id,action:f.get('action'),reason:f.get('reason')}:{requestId:selected.id,reason:f.get('reason')});await load();setMessage('Recovery action audited.');})}>{kind==='jobs'&&<label className="field">Action<select name="action"><option value="retry">Retry safe workflow</option><option value="cancel">Pause campaign dispatch</option></select></label>}<label className="field">Recovery reason<textarea name="reason" required minLength={10} maxLength={500}/></label><Button disabled={pending}>Execute approved workflow</Button></form></section>}
  <Button disabled={pending} variant="secondary" onClick={()=>void act(()=>load())}>Refresh</Button>{data.dataAsOf&&<p>Updated {new Date(data.dataAsOf).toLocaleString('en-PK')}</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error-text">{error}</p>}
 </>;
}
