import { type Screen, f, required, select, integer, moneyField, check, branches, branch, reason, action, save, when, policy } from './contracts';
import { staff, branding, branchDetails } from './staff-owner';

const messageFields = () => [f('title', 'Notification title', { required: true, min: 3, max: 80 }), f('body', 'Notification message', { kind: 'textarea', required: true, min: 10, max: 500 })];
export const operationScreens: Screen[] = [
  { id: 'O09', title: 'Campaigns', role: 'manager', capability: 'campaigns', routes: ['/dashboard/[businessId]/campaigns'], description: 'Reach consenting members with timely messages.', report: true, tables: ['campaigns', 'campaign_recipients', 'delivery_attempts'], operations: ['list campaigns', 'pause/resume/cancel/duplicate campaign'], sections: [
    { title: 'Campaign list', fields: [select('status', 'Status', ['All', 'Draft', 'Scheduled', 'Processing', 'Paused', 'Canceled', 'Completed', 'Completed with errors', 'Failed'], 'All')], columns: ['Name', 'Status', 'Scheduled time / timezone', 'Unique audience', 'Provider-accepted device sends', 'Failures', 'Observed clicks', 'Fulfilled claims'], empty: 'Create your first campaign after members opt in.', notes: ['Zero consent-eligible members means zero audience. Provider acceptance does not prove delivery or reading.'], actions: [action('Create campaign', { to: 'O10' }), action('View report', { to: 'O15' }), action('Edit draft', { to: 'O10' }), action('Pause', { confirm: 'Stop new attempts? Already accepted notifications cannot be recalled.' }), action('Resume before expiry'), action('Cancel', { confirm: 'Cancel future processing of this campaign?' }), action('Duplicate')] },
  ] },
  { id: 'O10', title: 'Compose a campaign', role: 'manager', capability: 'campaigns', routes: ['/dashboard/[businessId]/campaigns/new', '/dashboard/[businessId]/campaigns/[id]/edit'], description: 'Preview content, audience and timing before scheduling.', tables: ['campaigns', 'campaign_versions', 'campaign_branches', 'push_test_registrations'], operations: ['save campaign', 'estimate audience', 'register test device', 'schedule campaign'], sections: [
    { title: 'Message', fields: [required('campaignName', 'Internal campaign name', 2, 100), ...messageFields(), f('image', 'Image', { kind: 'file' }), select('destination', 'Destination', ['My loyalty card', 'Offer'], 'My loyalty card'), { ...select('offer', 'Offer', ['Sample published offer']), when: when('destination', 'Offer') }], notes: ['Plain text only. Length counts trimmed Unicode characters, including each emoji once. OS previews may truncate; full text remains at the destination.'] },
    { title: 'Audience and timing', fields: [select('audience', 'Audience', ['All opted in', 'Inactive', 'Reward ready', 'Near reward'], 'All opted in'), { ...integer('inactiveDays', 'Inactive days', 7, 365, '30'), when: when('audience', 'Inactive') }, { ...select('targetReward', 'Target reward', ['Sample published reward']), when: when('audience', 'Reward ready', 'Near reward') }, { ...integer('unitsAway', 'Units away from reward', 1, 1000), when: when('audience', 'Near reward') }, branches(), select('sendTime', 'Send time', ['Now', 'Schedule'], 'Now'), f('scheduledAt', 'Scheduled date/time', { kind: 'datetime-local', required: true, when: when('sendTime', 'Schedule') }), f('expiresAt', 'Stop sending after', { kind: 'datetime-local', required: true })], notes: ['Branches mean recorded affiliation, not live location. Card messages default to a 24-hour send window, maximum seven days. Offer messages stop no later than the offer expiry.', policy.caps] },
    { title: 'Audience estimate', readouts: ['Eligible members', 'Subscribed devices', 'Consent exclusions', 'Invalid-token exclusions', 'Cap exclusions', 'Branch exclusions'], notes: ['Estimates are provisional until the server snapshots the audience. Consent is rechecked before every send.'], actions: [save(), save('Preview audience'), action('Review and schedule/send', { validate: true, confirm: 'Review the business, audience, message, destination and schedule. No customers are messaged by this fixture.' })] },
    { title: 'My test device', readouts: ['Pending / Registered / Failed', 'Provider acceptance'], notes: ['Only your own challenge-verified test device is eligible. Test devices do not count as customer audience.'], actions: [action('Register this browser as my test device'), action('Send test to my registered test device'), action('Retry registration'), action('Remove device')] },
  ] },
  { id: 'O11', title: 'Offers', role: 'manager', capability: 'campaigns', routes: ['/dashboard/[businessId]/offers', '/dashboard/[businessId]/offers/[id]'], description: 'Define an offer with clear conditions and validity.', tables: ['offers', 'offer_branches', 'offer_recipients'], operations: ['save/publish/pause/duplicate offer'], sections: [
    { title: 'Offer list', columns: ['Title', 'Kind', 'Validity', 'Branches', 'Status', 'Claims', 'Fulfillments'], empty: 'Create an informational, discount or treat offer.', actions: [action('Create offer'), action('View offer'), action('Edit draft')] },
    { title: 'Offer editor', fields: [required('offerTitle', 'Offer title', 2, 80), select('kind', 'Offer kind', ['Informational', 'Discount', 'Treat'], 'Informational'), f('description', 'Description', { kind: 'textarea', required: true, min: 1, max: 1000 }), f('terms', 'Terms', { kind: 'textarea', max: 2000, help: 'Claimable offers require 10–2000 characters. A treat description must state the physical benefit.' }), f('image', 'Image', { kind: 'file' }), branches(), f('startsAt', 'Start date/time', { kind: 'datetime-local', required: true }), f('expiresAt', 'End date/time', { kind: 'datetime-local', required: true }), select('audience', 'Audience', ['All members', 'Specific recipients'], 'All members'), f('recipients', 'Selected members', { kind: 'multi', required: true, options: ['Sample member'], max: 1000, when: when('audience', 'Specific recipients') }), { ...moneyField('minimumSpend', 'Minimum eligible spend (Rs)', '0'), when: when('kind', 'Discount', 'Treat') }, { ...integer('percent', 'Discount percent', 1, 100), when: when('kind', 'Discount') }, { ...moneyField('discountCap', 'Maximum discount (Rs)'), required: false, when: when('kind', 'Discount') }], notes: ['Informational offers have no claim or discount fields. Published or claimed economic terms are protected; duplicate for material changes. Birthday templates are recipient-list templates, never publicly claimable. Annual instances are read-only and cannot be reassigned.'], actions: [save(), save('Publish offer'), action('Duplicate'), action('Pause', { confirm: 'Stop new claims and sends? Existing claims remain fulfillable until their original expiry.' })] },
  ] },
  { id: 'O12', title: 'Automations', role: 'owner', routes: ['/dashboard/[businessId]/automations'], description: 'Useful reminders with consent, quiet hours and duplicate suppression.', tables: ['automation_rules', 'automation_runs'], operations: ['save/disable automation', 'preview rendered sample'], sections: [
    { title: 'Configure automation', fields: [select('kind', 'Automation', ['Reward available', 'Inactivity', 'Birthday'], 'Reward available'), check('enabled', 'Enabled'), { ...select('targetReward', 'Target reward', ['Sample published reward']), when: when('kind', 'Reward available') }, { ...integer('inactiveDays', 'Inactive days', 7, 365, '30'), when: when('kind', 'Inactivity') }, { ...select('publishedOffer', 'Published offer', ['None', 'Sample published offer'], 'None'), required: false, when: when('kind', 'Inactivity') }, { ...select('birthdayTemplate', 'Birthday offer template', ['Sample recipient-list treat template']), when: when('kind', 'Birthday') }, { ...integer('validityDays', 'Birthday validity days', 1, 30, '7'), when: when('kind', 'Birthday') }, ...messageFields()], readouts: ['Last run', 'Suppressed count', 'Failed count'], notes: ['Reward available runs once per qualifying crossing. Inactivity runs after the last qualifying purchase, once until the next purchase. Birthday creates a private member/year instance using the cafe timezone, inbox consent and separate birthday-push consent.', policy.caps, 'Rendered titles and messages must also meet the displayed character limits. No eligible recipients is a successful scan, not an error.'], actions: [action('Create birthday template', { to: 'O11' }), save('Preview sample'), save('Save'), action('Disable', { confirm: 'Disable this automation for future runs?' })] },
    { title: 'Run history', columns: ['Timestamp', 'Kind', 'Status', 'Suppression / error summary'], empty: 'No automation runs yet.' },
  ] },
  { id: 'O13', title: 'WhatsApp follow-ups', role: 'manager', capability: 'contacts', routes: ['/dashboard/[businessId]/whatsapp/templates', '/dashboard/[businessId]/whatsapp/new'], description: policy.manual, tables: ['whatsapp_templates', 'followup_batches', 'followup_tasks'], operations: ['save template', 'preview/create follow-up batch'], sections: [
    { title: 'Template', fields: [required('templateName', 'Template name', 2, 80), f('templateBody', 'Template body', { kind: 'textarea', required: true, min: 10, max: 1000, help: 'Supported tokens: {{first_name}}, {{business_name}}, {{reward_name}}, {{public_offer_url}}. Missing values and unknown tokens block task creation.' })], actions: [save('Save template')] },
    { title: 'Create follow-up tasks', fields: [required('batchName', 'Batch name', 2, 100), select('template', 'Template', ['Sample template']), select('audience', 'Audience', ['Selected members', 'Inactive', 'Reward ready'], 'Selected members'), f('members', 'Selected members', { kind: 'multi', required: true, options: ['Sample member'], when: when('audience', 'Selected members') }), { ...integer('inactiveDays', 'Inactive days', 7, 365, '30'), when: when('audience', 'Inactive') }, { ...select('targetReward', 'Target reward', ['Sample reward']), required: false, help: 'Required for reward-ready audience or a reward_name token.' }, { ...select('offer', 'Public offer', ['Sample all-members offer']), required: false, help: 'Required for a public_offer_url token.' }, { ...select('assignee', 'Assigned staff', ['Unassigned', 'Sample authorized manager'], 'Unassigned'), required: false }], readouts: ['Consent-eligible contacts', 'Validation exclusions', 'Recent-contact warnings', 'Rendered message preview', 'Manual task count'], notes: ['Only owners or managers with contact permission can create or execute tasks. Cashiers cannot be assigned. Rendered text is never silently truncated.'], actions: [save('Preview tasks'), save('Create follow-up tasks')] },
  ] },
  { id: 'O14', title: 'Manual WhatsApp tasks', role: 'manager', capability: 'contacts', routes: ['/dashboard/[businessId]/whatsapp', '/dashboard/[businessId]/whatsapp/tasks/[id]'], description: policy.manual, report: true, tables: ['followup_tasks', 'followup_events', 'membership_contacts'], operations: ['lease task', 'open chat', 'mark sent', 'skip', 'record opt-out', 'reassign'], sections: [
    { title: 'Task list', fields: [f('batch', 'Batch'), select('status', 'Task status', ['All', 'Pending', 'Assigned', 'Opened', 'Staff marked sent', 'Skipped', 'Opted out'], 'All'), { ...select('assignee', 'Assignee', ['All', 'Me'], 'All'), required: false }], columns: ['Customer', 'Reason / batch', 'Assigned staff', 'Last contact', 'Status'], empty: 'No manual tasks. Create a follow-up batch for consenting contacts.', actions: [action('Create follow-up', { to: 'O13' })] },
    { title: 'Task detail', readouts: ['Message preview', 'Current consent', 'Authorized number', 'Verification status', 'Recent communication history', 'Task lease owner / expiry'], fields: [f('skipReason', 'Skip reason', { max: 500 }), f('optoutNote', 'Opt-out source and note', { min: 1, max: 500 })], notes: ['Opened and staff-marked-sent are distinct. A changed phone, revoked consent or stale task blocks chat generation; refresh or skip. The app cannot verify which WhatsApp account is open.'], actions: [action('Open WhatsApp'), action('Mark as sent', { confirm: 'Confirm you personally sent this message in the cafe’s WhatsApp account. The app cannot observe sending, delivery or reading.' }), action('Skip'), action('Record opt-out', { validate: true, confirm: 'Record this customer’s opt-out and immediately suppress pending tasks?' }), action('Reassign')] },
  ] },
  { id: 'O15', title: 'Reports', role: 'manager', routes: ['/dashboard/[businessId]/reports'], description: 'Current, scoped figures from recorded activity.', tabs: ['Overview', 'Customers', 'Rewards', 'Referrals', 'Double slots', 'Campaigns', 'Staff'], report: true, tables: ['purchases', 'ledger_entries', 'redemptions', 'referral_claims', 'campaign_recipients', 'delivery_attempts', 'followup_events'], operations: ['active report query', 'export report'], sections: [
    { title: 'Report selection', fields: [f('programme', 'Programme filter'), f('reward', 'Reward filter'), f('promotion', 'Promotion filter'), f('campaign', 'Campaign filter')], notes: ['Fetch only the active tab. Reports query source data directly. A failed refresh clears old results; narrow the range or retry. Counts and sales include reversals as defined in metric definitions.'], readouts: ['Updated time'], actions: [action('Refresh'), action('Metric definitions'), action('Export CSV', { capability: 'exports', confirm: 'Review the report, date range, permitted branches and selected columns. Personal contact data is excluded by default. Downloads are private and expire.' })] },
    { title: 'Report data', columns: ['Metric', 'Value', 'Definition'], empty: 'No report has been loaded. Missing data is not zero.', notes: ['Overview: net recorded sales, purchase counts, new/purchasing/returning members and average recorded bill. Customers: repeat, never-purchased and inactive segments. Rewards: base/bonus/referral units, fulfillment, reversals, outstanding units and estimated cost coverage.', 'Referrals: enrolled, qualified, capped, expired, reversed and bonuses. Double slots: slot/version, purchases, eligible spend, bonus and reversals. Campaigns: unique audience, device attempts, observed clicks, claims and associated purchases. Staff: scoped purchases, awards, redemptions and reversals.', 'Unknown costs and zero denominators are N/A. WhatsApp reports opened and staff-marked-sent only. Associated sales do not prove causal campaign uplift.'] },
  ] },
  { id: 'O16', title: 'Staff', role: 'owner', routes: ['/dashboard/[businessId]/staff'], description: 'Individual accounts and explicit branch permissions.', tables: ['business_users', 'staff_invitations', 'branch_assignments', 'invitation_branches'], operations: ['invite/revoke staff', 'edit assignments'], sections: [
    { title: 'Active staff', columns: ['Name / staff email', 'Role', 'Branches', 'Manager permissions', 'Status', 'Last relevant activity'], empty: 'Invite your first team member.', actions: [action('Edit assignment'), action('Revoke access', { confirm: 'Revoke this staff member’s access? The next operation must be denied, even with an old session.' })] }, staff,
    { title: 'Pending invitations', columns: ['Email', 'Role', 'Branches', 'Expiry', 'Status'], empty: 'No pending invitations.', actions: [action('Resend pending invite'), action('Revoke invite', { confirm: 'Revoke this unused invitation?' })], notes: ['No owner self-demotion, self-deletion or ownership transfer control. No shared cashier PIN.'] },
  ] },
  { id: 'O17', title: 'Branches', role: 'owner', routes: ['/dashboard/[businessId]/branches', '/dashboard/[businessId]/branches/[id]'], description: 'Accurate public details and scoped operations.', tables: ['branches', 'branch_hours'], operations: ['save/deactivate branch'], sections: [branchDetails,
    { title: 'Branch usage', readouts: ['Staff assignment count', 'Programme usage', 'Reward usage', 'Promotion usage', 'Plan branch limit'], notes: ['Pause enrollment before deactivating the only active public branch. Historical ledger and reports retain their branch. Extra outlets require plan entitlement.'], actions: [save('Save'), action('Public page preview', { to: 'P02' }), action('Deactivate branch', { confirm: 'Deactivate this branch for future activity? History remains attached. The last active public branch cannot be disabled without pausing enrollment.' })] },
  ] },
  { id: 'O18', title: 'Business settings', role: 'owner', routes: ['/dashboard/[businessId]/settings'], description: 'Your cafe’s identity and public signup assets.', tables: ['businesses', 'media_assets', 'policy_documents'], operations: ['save settings', 'generate public QR', 'pause/resume participation'], sections: [
    { ...branding, fields: [...branding.fields!.filter(field => field.id !== 'slug'), f('phone', 'Public phone', { kind: 'phone' }), f('email', 'Support email', { kind: 'email', max: 254 }), f('menu', 'Menu URL', { kind: 'url' }), f('review', 'Neutral review URL', { kind: 'url' }), f('timezone', 'Timezone', { required: true, initial: 'Asia/Karachi', help: 'Locked after live financial or scheduled activity.' })], readouts: ['Published slug', 'Currency: PKR', 'Current consent / terms versions'], notes: ['Accepted images only. Merchant accents affect cards; controls keep the platform theme. Reviews use the same neutral request for all customers and never earn points.'], actions: [save('Save settings')] },
    { title: 'Signup QR assets', fields: [branch()], readouts: ['Public destination', 'Cafe name', 'Reward proposition', 'Scan instructions', 'Readable short URL'], notes: ['Signage uses only public signup links, never personal earning or intent codes. Standard NFC tags may hold the same public signup URL. No special reader is required.'], actions: [action('Download PNG'), action('Download printable PDF/SVG')] },
    { title: 'Participation', actions: [action('Pause participation', { confirm: 'Pause new participation under the access policy? Customer balances and history are retained.' }), action('Resume participation', { confirm: 'Resume participation after entitlement and publication checks?' })] },
  ] },
  { id: 'O19', title: 'Billing', role: 'owner', routes: ['/dashboard/[businessId]/billing', '/dashboard/[businessId]/billing/invoices/[id]'], description: 'Plan access changes only after verified payment.', tables: ['subscriptions', 'plan_versions', 'invoices', 'payment_submissions'], operations: ['submit payment evidence', 'cancel renewal'], sections: [
    { title: 'Current plan', readouts: ['Plan and version', 'Price and billing interval', 'Subscription state', 'Billing period', 'Due / grace date', 'Branch usage / limit', 'Staff usage / limit', 'Member usage / limit', 'Campaign usage / limit'] },
    { title: 'Invoices', columns: ['Reference', 'Covered period', 'Amount', 'Due date', 'Status'], empty: 'No invoices available.', actions: [action('View/download invoice')] },
    { title: 'Submit payment evidence', fields: [moneyField('claimedAmount', 'Claimed amount (Rs)'), select('method', 'Payment method', ['Bank transfer', 'Merchant wallet']), required('transferReference', 'Transfer reference', 1, 200), f('proof', 'Proof image', { kind: 'file' })], readouts: ['Configured payment instructions', 'Pending / accepted / rejected review status', 'Review reason'], notes: ['Your plan updates after payment is verified. Payment instructions must be configured by the operator. Paid invoices are not editable.'], actions: [save('Submit for review')] },
    { title: 'Plan changes', actions: [action('Request plan change'), action('Cancel renewal', { confirm: 'Cancel renewal at the end of the current period? Review future access policy; balances and history are retained.' })] },
  ] },
  { id: 'A01', title: 'Platform overview', role: 'admin', routes: ['/admin'], description: 'Audited platform operations. Verified MFA is required.', tables: ['businesses', 'subscriptions', 'invoices', 'operational_checks'], operations: ['platform health summary'], sections: [
    { title: 'Recorded platform health', readouts: ['Active businesses', 'Trial businesses', 'Past-due businesses', 'Reviewed invoices', 'Unreviewed invoices', 'Job backlog / oldest job', 'Recent failed campaigns', 'Ledger reconciliation', 'Last successful backup', 'Last restore rehearsal'], notes: ['Missing operational evidence is Unknown. No unrestricted customer directory.'], actions: [action('Tenants', { to: 'A02' }), action('Billing', { to: 'A04', capability: 'billing' }), action('Plans', { to: 'A03' }), action('Jobs', { to: 'A05' }), action('Audit / Privacy', { to: 'A06' })] },
  ] },
  { id: 'A02', title: 'Tenants', role: 'admin', routes: ['/admin/businesses', '/admin/businesses/[id]'], description: 'Manage participation without silent impersonation.', tables: ['businesses', 'subscriptions', 'support_access_grants'], operations: ['tenant operations', 'start support grant'], sections: [
    { title: 'Tenant list', fields: [select('status', 'Business status', ['All', 'Draft', 'Active', 'Paused', 'Archived'], 'All'), f('plan', 'Plan'), select('subscription', 'Subscription', ['All', 'Trial', 'Active', 'Past due', 'Suspended', 'Canceled'], 'All')], columns: ['Business / slug', 'Owner business account', 'Branches', 'Subscription', 'Created', 'Operational flags'], empty: 'No tenants loaded.' },
    { title: 'Tenant detail', readouts: ['Configuration', 'Usage', 'Invoices', 'Limited operational history'], fields: [reason()], notes: ['Suspension changes participation access; customer balances/history remain protected. Plan changes require billing verification.'], actions: [action('Pause publishing', { confirm: 'Pause new public participation for this tenant?' }), action('Resume publishing'), action('Change permitted plan after billing verification', { capability: 'billing' }), action('Suspend', { validate: true, confirm: 'Suspend this business with the recorded reason? Review the displayed customer-access consequences before applying.' })] },
    { title: 'Audited support', capability: 'support', fields: [{ ...reason(), id: 'supportReason' }, select('scope', 'Support scope', ['Configuration', 'Transaction support']), select('duration', 'Duration (minutes)', ['15', '30', '60'], '15')], notes: ['Requires MFA and reauthentication within 15 minutes. No silent owner/customer impersonation or bulk contact exports.'], actions: [action('Start support session', { validate: true, confirm: 'Create an audited, time-limited grant for this exact tenant and scope?' })] },
  ] },
  { id: 'A03', title: 'Plans', role: 'admin', routes: ['/admin/plans'], description: 'Versioned published pricing and explicit entitlements.', tables: ['plans', 'plan_versions'], operations: ['save/publish plan version'], sections: [
    { title: 'Plan editor', fields: [required('planCode', 'Plan code', 1, 80), required('planName', 'Plan name', 2, 80), select('interval', 'Billing interval', ['Monthly', 'Annual'], 'Monthly'), { ...moneyField('price', 'Price (Rs)'), min: 0.01 }, integer('branchLimit', 'Branch limit', 1, 2147483647), integer('staffLimit', 'Staff limit', 1, 2147483647), { ...integer('memberLimit', 'Member limit', 1, 2147483647), required: false, help: 'Blank means unlimited by plan; system safeguards still apply.' }, { ...integer('campaignLimit', 'Monthly campaign limit', 1, 2147483647), required: false, help: 'Blank means unlimited by plan.' }, integer('trialDays', 'Trial days', 0, 30, '14'), check('active', 'Active')], readouts: ['Included: referrals, double slots, reporting, manual WhatsApp'], notes: ['Publish a new immutable version. Historical subscriptions and invoices do not silently change.'], actions: [save(), save('Publish plan version')] },
  ] },
  { id: 'A04', title: 'Billing review', role: 'admin', capability: 'billing', routes: ['/admin/billing', '/admin/billing/[invoiceId]'], description: 'Reconcile actual bank/provider records, not screenshots alone.', tables: ['payment_submissions', 'payment_events', 'invoices', 'subscriptions'], operations: ['confirm/reject payment', 'correct verified payment'], sections: [
    { title: 'Review queue', columns: ['Business', 'Invoice', 'Claimed amount', 'Expected amount', 'Submitted', 'Method', 'Review state'], empty: 'No payment submissions loaded.', readouts: ['Authenticated proof', 'Existing payment references'] },
    { title: 'Reconciliation', fields: [moneyField('verifiedAmount', 'Verified amount (Rs)'), required('provider', 'Bank/provider name', 1, 100), required('externalReference', 'External reference', 1, 200), select('decision', 'Decision', ['Confirm', 'Reject'], 'Confirm'), f('reviewNote', 'Review note', { kind: 'textarea', max: 500, help: 'Required on rejection or amount mismatch.' }), { ...check('reconciled', 'I reconciled the actual bank/provider record'), required: true, when: when('decision', 'Confirm') }], notes: ['Fresh MFA is required. Full invoice amount must match; duplicate external references are blocked. Exactly one payment event updates coverage.'], actions: [action('Confirm payment', { validate: true, confirm: 'Confirm actual reconciliation for the exact invoice amount and external reference? This affects subscription coverage.' }), save('Reject submission')] },
    { title: 'Verified-payment correction', fields: [reason()], readouts: ['Original amount / invoice', 'Projected invoice and access effect'], notes: ['Available only for a confirmed, uncorrected event. Fresh MFA required. Creates a compensating event; paid history is not edited.'], actions: [action('Correct verified payment', { validate: true, confirm: 'Apply a compensating correction once to this verified payment? Review the resulting invoice and access state.' })] },
  ] },
  { id: 'A05', title: 'Jobs and incidents', role: 'admin', routes: ['/admin/jobs'], description: 'Redacted diagnostics and bounded recovery.', report: true, tables: ['outbox_events', 'operational_checks', 'delivery_attempts'], operations: ['job diagnostics', 'retry valid job', 'cancel dispatch'], sections: [
    { title: 'Jobs', fields: [f('jobType', 'Job/event type'), f('state', 'State'), f('business', 'Business')], columns: ['Event key', 'Safe entity reference', 'Attempts', 'Next attempt', 'Age', 'Error code', 'Status'], empty: 'No jobs loaded.', notes: ['Logs omit auth tokens, push tokens and customer message dumps. Retries never override consent or expiry.'], actions: [action('Retry', { confirm: 'Retry only if still valid and retryable. A provider-unknown send may already have been accepted; apply the deduplication policy.' }), action('Cancel dispatch', { confirm: 'Pause future processing? Already accepted sends cannot be recalled.' })] },
    { title: 'Independent health checks', readouts: ['Worker heartbeat', 'Database readiness', 'Provider failure status', 'Backup status'] },
  ] },
  { id: 'A06', title: 'Audit and privacy', role: 'admin', routes: ['/admin/audit', '/admin/privacy'], description: 'Append-only accountability and controlled data workflows.', report: true, tables: ['audit_events', 'privacy_requests', 'export_requests'], operations: ['scoped audit', 'execute authorized privacy workflow'], sections: [
    { title: 'Audit', fields: [f('actor', 'Actor'), f('business', 'Business'), f('action', 'Action'), f('supportSession', 'Support session')], columns: ['Timestamp', 'Actor', 'Action', 'Tenant', 'Target', 'Reason', 'Correlation ID'], empty: 'No audit events loaded. Records cannot be edited or deleted.' },
    { title: 'Privacy requests', columns: ['Reference', 'Type', 'Requested', 'Status', 'Authorized subject context', 'Completion / error'], empty: 'No privacy requests loaded.', readouts: ['Retained categories', 'Recovery action'], notes: ['Downloads expire and are restricted to the requester or a narrowly authorized support procedure. Failed deletion must not claim complete erasure.'], actions: [action('Execute approved workflow', { confirm: 'Execute this approved, scoped export or anonymization request? Required history may be retained privately.' })] },
  ] },
];
