import { type Screen, f, required, select, integer, check, branch, action, save, when } from './contracts';

export const publicCustomerScreens: Screen[] = [
  { id: 'P01', title: 'A reason to return', role: 'visitor', routes: ['/'], description: 'One shared loyalty app. Each cafe’s own rewards.', tables: ['plan_versions', 'policy_documents'], operations: ['published plans'], sections: [
    { title: 'Scan, earn, redeem', notes: ['Scan the cafe QR, join, and show your personal card at checkout. Referrals qualify after purchases. Double slots, reports, and manual WhatsApp are included in the planned launch.'], actions: [action('Start your cafe trial', { to: 'P03' })] },
    { title: 'Contact us for pricing', notes: ['Published PKR prices, billing periods and limits appear after configuration. Installation and notifications are optional. Staff press Send for every WhatsApp message.'] },
  ] },
  { id: 'P02', title: 'Your neighbourhood cafe', role: 'visitor', routes: ['/b/[slug]'], description: 'A little thank you for your next visit.', tables: ['businesses', 'branches', 'branch_hours', 'programme_versions', 'reward_versions', 'offers'], operations: ['public business projection'], sections: [
    { title: 'Your next reward', readouts: ['Cafe logo and cover', 'Description', 'Reward headline', 'Programme type', 'Required units', 'Qualifying purchase terms'], actions: [action('Join loyalty programme', { to: 'P05' }), action('Open my card', { to: 'C02' })] },
    { title: 'Visit us', fields: [branch()], readouts: ['Branch address', 'Opening hours'], notes: ['Menu, directions and contact links appear only when the cafe supplies them. A single active branch is preselected.'] },
    { title: 'Public offers', columns: ['Offer', 'Validity', 'Qualification'], empty: 'No public offers at the moment.' },
    { title: 'Join through a friend’s referral', notes: ['Your first qualifying purchase can earn bonus stamps or points under the cafe’s current terms. Referral benefits and amounts appear only after validation.'], actions: [action('Remove referral')] },
  ] },
  { id: 'P03', title: 'Welcome back.', role: 'visitor', routes: ['/auth/login'], description: 'Choose Google or a verified email link.', tables: ['auth.users'], operations: ['Google OAuth', 'email sign-in'], sections: [
    { title: 'Sign in', fields: [f('email', 'Email address', { kind: 'email', required: true, max: 254 })], readouts: ['Customer or business destination'], notes: ['Your sign-in destination does not grant a business role. Sign-in does not opt you into marketing.'], actions: [action('Continue with Google'), save('Send sign-in link')] },
  ] },
  { id: 'P04', title: 'Finish signing in', role: 'customer', routes: ['/auth/complete', '/invite/[token]', '/auth/mfa'], description: 'Complete your profile and secure access.', tables: ['profiles', 'staff_invitations', 'invitation_branches', 'auth.mfa_factors'], operations: ['complete_profile', 'accept invitation', 'MFA enroll/challenge/verify'], sections: [
    { title: 'Your name', fields: [required('displayName', 'Display name', 1, 80)], actions: [save('Save and continue')] },
    { title: 'Invitation', readouts: ['Business', 'Inviter', 'Proposed role', 'Permitted branches', 'Expiry'], notes: ['Sign in with the verified email the invitation was sent to. An invitation can only be accepted once.'], actions: [action('Accept invitation'), action('Switch account', { to: 'P03' })] },
    { title: 'Authenticator', fields: [f('mfa', 'Six-digit verification code', { kind: 'code', required: true, min: 6, max: 6 })], readouts: ['Authenticator QR', 'Manual setup key'], notes: ['An authenticator setup key is shown only after secure enrollment. Use the provider’s recovery procedure; there is no MFA bypass.'], actions: [action('Set up authenticator'), save('Verify and continue')] },
    { title: 'Invalid or expired link', actions: [action('Request a new link', { to: 'P03' })] },
  ] },
  { id: 'P05', title: 'Join the loyalty programme', role: 'customer', routes: ['/join/[slug]'], description: 'Keep this cafe’s rewards on your own card.', tables: ['memberships', 'membership_contacts', 'consent_preferences', 'enrollment_acceptances'], operations: ['enroll membership', 'rejoin membership'], sections: [
    { title: 'Programme and referral terms', readouts: ['Programme', 'Next reward', 'Qualifying referral rules', 'Programme terms version'], notes: ['Participation can pause; your balance and history are retained. Marketing is optional.'], actions: [action('Access policy', { to: 'P07' })] },
    { title: 'Your card', fields: [required('displayName', 'Display name'), branch(), check('shareEmail', 'Share my email with this cafe'), f('phone', 'WhatsApp number', { kind: 'phone', help: 'Only needed if you want WhatsApp follow-ups. This number remains unverified.' }), check('whatsapp', 'Receive WhatsApp offers from this cafe'), { ...check('terms', 'I accept the programme terms'), required: true }], actions: [save('Join and view my card')] },
  ] },
  { id: 'P06', title: 'Choose your workspace', role: 'customer', routes: ['/workspace'], description: 'Use your cards or open a business you work with.', tables: ['business_users', 'branch_assignments', 'platform_admins'], operations: ['list authorized workspaces'], sections: [
    { title: 'Your businesses', columns: ['Business', 'Role', 'Branches'], empty: 'No active business workspaces. Create a business to begin onboarding.', actions: [action('Create business', { to: 'O01' }), action('My loyalty cards', { to: 'C01' }), action('Open dashboard', { to: 'O02', roles: ['owner', 'manager'] }), action('Open scanner', { to: 'S01', roles: ['cashier'] }), action('Admin', { to: 'A01', roles: ['admin'] }), action('Sign out')] },
  ] },
  { id: 'P07', title: 'Policies', role: 'visitor', routes: ['/privacy', '/terms'], description: 'Published privacy and programme access information.', tables: ['policy_documents'], operations: ['published policy document'], sections: [{ title: 'Policy publication pending', readouts: ['Document version', 'Effective date', 'Support contact'], notes: ['Live enrollment and publication require the actual published terms and privacy notice. No legal text has been invented for this preview.'] }] },
  { id: 'C01', title: 'Cards', role: 'customer', routes: ['/app'], description: 'Your cafes. Your separate rewards.', tables: ['memberships', 'balances', 'rewards'], operations: ['list own cards'], sections: [
    { title: 'My loyalty cards', fields: [f('search', 'Search my joined cafes')], empty: 'Your loyalty cards will appear here. Scan a cafe’s QR code to join.', actions: [action('Open card', { to: 'C02' })] },
    { title: 'Keep your cards handy', notes: ['After your first card, you can install the shared app. Installation is optional.'], actions: [action('Install guidance'), action('Not now')] },
  ] },
  { id: 'C02', title: 'Your loyalty card', role: 'customer', routes: ['/app/cards/[membershipId]'], description: 'Show this at checkout.', tables: ['memberships', 'membership_handles', 'balances', 'ledger_entries', 'promotion_versions'], operations: ['own card', 'rotate handle', 'create lookup code'], sections: [
    { title: 'Checkout QR', readouts: ['Cafe and branch', 'Personal earning QR', 'Current balance', 'Progress', 'Next reward and cost', 'Active double-slot hours and branches'], notes: ['Your earning QR cannot authorize a reward redemption. Saved checkout screenshots stop working when you replace your QR.'], actions: [action('View rewards', { to: 'C03' }), action('Get checkout code'), action('Replace checkout QR', { confirm: 'Replace your checkout QR? Saved screenshots will stop working. Your balance and history stay the same.' })] },
    { title: 'Recent activity', columns: ['Date', 'Type', 'Signed units'], empty: 'Your latest ten activities will appear here.' },
    { title: 'More from this cafe', actions: [action('Refer a friend', { to: 'C05' }), action('Offer inbox', { to: 'C04' }), action('Notification preferences', { to: 'C07' }), action('Enable reward reminders'), action('Programme terms', { to: 'P07' })] },
  ] },
  { id: 'C03', title: 'Rewards', role: 'customer', routes: ['/app/cards/[membershipId]/rewards'], description: 'Choose a reward, then show its short-lived code to staff.', tables: ['reward_versions', 'reward_branches', 'redemption_intents', 'redemptions'], operations: ['list rewards', 'create/cancel redemption intent'], sections: [
    { title: 'Available rewards', readouts: ['Title', 'Description', 'Required units', 'Eligible branches', 'Terms', 'Availability'], actions: [action('Use this reward', { confirm: 'Generate a short-lived reward code? No points are deducted until staff confirm fulfillment.' })] },
    { title: 'Show this to staff', readouts: ['Reward name', 'Units to be used', 'Short-lived QR and code', 'Time remaining'], notes: ['No points deducted yet. Creating a replacement invalidates the previous active code for this reward.'], actions: [action('Cancel'), action('Generate a new code')] },
    { title: 'Fulfillment receipt', readouts: ['Redeemed timestamp', 'Cafe and branch', 'Debited units', 'New balance'] },
  ] },
  { id: 'C04', title: 'Offers', role: 'customer', routes: ['/app/offers', '/app/offers/[offerId]'], description: 'Offers from cafes you have joined.', tables: ['offers', 'offer_recipients', 'offer_claims', 'offer_claim_intents'], operations: ['own offers', 'claim offer', 'create/cancel claim intent'], sections: [
    { title: 'My offers', fields: [select('cafe', 'Cafe', ['All my cafes', 'Sample cafe'], 'All my cafes'), select('status', 'Status', ['Active', 'Expired', 'Fulfilled'], 'Active')], columns: ['Cafe', 'Offer', 'Valid until', 'Qualification'], empty: 'No active offers. Check back after joining a cafe.' },
    { title: 'Offer details', readouts: ['Image', 'Description', 'Terms', 'Dates and times', 'Timezone', 'Branches', 'Minimum spend', 'Discount and cap or treat', 'Eligibility'], notes: ['A claim is not fulfillment. Staff validate the short-lived intent and purchase conditions. Informational offers open your card and cannot be claimed.'], actions: [action('Open my card', { to: 'C02' }), action('Claim offer'), action('Show at checkout'), action('Cancel claim presentation')] },
  ] },
  { id: 'C05', title: 'Referrals', role: 'customer', routes: ['/app/referrals'], description: 'Give a friend a reason to visit.', tables: ['referral_codes', 'referral_rule_versions', 'referral_claims'], operations: ['own referral link and results'], sections: [
    { title: 'Refer a friend', fields: [select('cafe', 'Joined cafe', ['Sample cafe'])], readouts: ['Inviter bonus', 'Friend’s bonus', 'Minimum qualifying spend', 'Qualification deadline', 'Monthly cap and usage'], notes: ['The friend’s configured benefit remains when the inviter cap is reached. Rewards follow a qualifying purchase, not signup. Paused rules disable new sharing; history remains visible.'], actions: [action('Copy referral link'), action('Share')] },
    { title: 'Referral history', readouts: ['Referred signups', 'Pending', 'Qualified', 'Earned inviter units', 'Reversed', 'Expired'], columns: ['Friend label', 'Date', 'Status', 'Bonus units'], empty: 'No referral activity yet. Your friends’ contact details stay private.' },
  ] },
  { id: 'C06', title: 'Account', role: 'customer', routes: ['/app/settings'], description: 'Your profile, devices and data preferences.', tables: ['profiles', 'privacy_requests', 'export_requests'], operations: ['update profile', 'request account export/deletion', 'logout'], sections: [
    { title: 'Profile', fields: [required('displayName', 'Display name'), check('updateNames', 'Also update my display name at my cafes'), f('timezone', 'Timezone', { required: true, initial: 'Asia/Karachi', help: 'Use an IANA timezone for notification quiet hours.' }), { ...integer('birthdayMonth', 'Birthday month', 1, 12), required: false }, { ...integer('birthdayDay', 'Birthday day', 1, 31), required: false }], readouts: ['Verified account email'], notes: ['Birthday is optional. After your first saved date, changes are limited to once every 365 days. Clearing it is allowed but does not reset the reward cooldown. Saving does not subscribe any cafe to birthday marketing.'], actions: [save('Save profile'), action('Manage cafe preferences', { to: 'C07' })] },
    { title: 'On this device', fields: [check('offline', 'Keep my cards available offline', 'Off by default. At most 20 cards / 1 MiB, for 24 hours. No contacts or redemption codes.')], actions: [action('Clear offline card data'), action('Sign out')] },
    { title: 'Your data', readouts: ['Request status', 'Requested date', 'Completed date', 'Numbered export parts', 'Retained categories'], actions: [action('Download my data', { confirm: 'Reauthenticate to request a private, expiring data export.' }), action('Delete my account', { confirm: 'Reauthenticate and confirm account deletion. Required financial and audit history is retained privately. Owners must contact support to resolve ownership first.' })] },
  ] },
  { id: 'C07', title: 'Cafe preferences', role: 'customer', routes: ['/app/cards/[membershipId]/preferences'], description: 'Choose what you share with this cafe.', tables: ['membership_contacts', 'consent_preferences', 'consent_events', 'privacy_requests'], operations: ['update own preferences', 'leave membership', 'request membership deletion'], sections: [
    { title: 'Notifications', readouts: ['Cafe', 'Joined date'], fields: [check('marketingPush', 'Promotional push notifications'), check('rewardPush', 'Reward update notifications'), check('birthday', 'Birthday offers', 'Requires a saved birthday; does not require browser push. Your birthday stays private.'), { ...check('birthdayPush', 'Birthday push notifications'), when: when('birthday', 'true') }] },
    { title: 'Contact sharing', fields: [f('phone', 'WhatsApp number', { kind: 'phone' }), check('whatsapp', 'Allow WhatsApp offers from this cafe'), check('shareEmail', 'Share my verified email with this cafe')], readouts: ['Phone verification status', 'Exact disclosed email'], notes: ['Changing your phone clears verification and WhatsApp consent. A fresh explicit opt-in is required.'], actions: [save('Save preferences')] },
    { title: 'Membership', readouts: ['Deletion request status'], actions: [action('Leave this loyalty programme', { confirm: 'Leave this cafe? Marketing stops. Your balance and history are retained, and rejoining restores the same card without a new referral reward.' }), action('Delete my data at this cafe', { confirm: 'Reauthenticate to erase shared contacts and request membership anonymization. Required private financial history is retained.' })] },
  ] },
];
