import { type Screen, type Section, f, required, select, integer, moneyField, check, branches, branch, reason, action, save, when, policy } from './contracts';

export const programme: Section = { title: 'Earning rules', fields: [required('programmeName', 'Programme name', 2, 80), select('mode', 'Programme type', ['Stamps', 'Points'], 'Stamps'), moneyField('minimumSpend', 'Minimum eligible spend (Rs)', '0'), { ...integer('stamps', 'Stamps per qualifying purchase', 1, 10, '1'), when: when('mode', 'Stamps') }, { ...moneyField('step', 'Spend step (Rs)', '100'), min: 1, when: when('mode', 'Points') }, { ...integer('units', 'Points per step', 1, 1000, '1'), when: when('mode', 'Points') }, integer('baseCap', 'Maximum base units per purchase', 1, 100000, '1000'), f('programmeTerms', 'Programme terms', { kind: 'textarea', required: true, min: 10, max: 3000 }), f('effectiveAt', 'Effective date/time', { kind: 'datetime-local', required: true }), { ...moneyField('exampleSpend', 'Example eligible spend (Rs)', '250'), required: false }], notes: ['Programme type locks after the first ledger entry. Published versions are immutable; changed rates affect future purchases only. Points = floor(eligible spend / spend step) × points per step, limited by the base cap.'], actions: [save(), save('Publish new earning rules'), action('Pause earning', { confirm: 'Pause new earning? Existing balances and permitted reward fulfillment remain governed by the participation policy.' }), action('Resume earning', { confirm: 'Resume earning under the current published rules?' })] };
export const reward: Section = { title: 'Reward editor', fields: [required('rewardTitle', 'Reward title', 2, 80), integer('rewardCost', 'Required units', 1, 1000000), f('rewardDescription', 'Reward description', { kind: 'textarea', max: 500 }), f('rewardTerms', 'Reward terms', { kind: 'textarea', required: true, min: 10, max: 2000 }), branches(), { ...moneyField('estimatedCost', 'Estimated fulfillment cost (Rs)'), required: false, help: 'Blank means unknown. This is a merchant cost estimate, not cash value for points.' }], notes: ['Published unit costs cannot be increased or earned commitments deleted. Add a separate reward for new economic terms.'], actions: [save(), save('Publish reward')] };
export const staff: Section = { title: 'Invite staff', fields: [f('staffEmail', 'Staff email', { kind: 'email', required: true, max: 254 }), select('staffRole', 'Staff role', ['Manager', 'Cashier'], 'Cashier'), branches(), ...['Campaign management', 'Customer follow-ups', 'Transaction reversals', 'Report exports'].map((label, i) => ({ ...check(`grant${i}`, label), when: when('staffRole', 'Manager') }))], notes: ['Permissions default off and take effect on the next server operation. Cashiers cannot receive manager permissions. Invitation expires after 72 hours.'], actions: [save('Invite staff')] };
export const branding: Section = { title: 'Business details', fields: [required('businessName', 'Business name', 2, 80), f('slug', 'Slug', { required: true, min: 3, max: 50, help: 'Lowercase letters, digits and hyphens. Availability is checked when saving; published slugs cannot change.' }), f('description', 'Description', { kind: 'textarea', max: 500 }), f('accent', 'Accent color', { kind: 'color', required: true, initial: '#166534' }), f('logo', 'Logo', { kind: 'file' }), f('cover', 'Cover image', { kind: 'file' })] };
export const branchDetails: Section = { title: 'Branch details', fields: [required('branchName', 'Branch name', 2, 80), required('address', 'Address', 5, 300), required('city', 'City', 2, 80), f('area', 'Area', { max: 80 }), f('maps', 'Maps URL', { kind: 'url' }), f('branchPhone', 'Branch phone', { kind: 'phone' }), select('branchStatus', 'Branch status', ['Active', 'Inactive'], 'Active')], notes: ['Asia/Karachi · Split overnight opening hours into separate day intervals. Closed days have no intervals.'] };

export const staffOwnerScreens: Screen[] = [
  { id: 'S01', title: 'Scan a customer', role: 'cashier', routes: ['/staff/[businessId]'], description: 'Select your branch, then scan the customer’s earning card.', tables: ['business_users', 'branch_assignments', 'scanner_codes'], operations: ['authorized scanner lookup'], sections: [
    { title: 'Current checkout', fields: [branch()], readouts: ['Business', 'Signed-in staff'], notes: ['An earning QR finds a card. Redemption requires a separate customer-authorized intent. Camera starts only when you choose Scan.'] },
    { title: 'Customer code', fields: [f('lookupCode', 'Eight-character customer code', { kind: 'code', required: true, min: 8, max: 8 })], actions: [save('Look up customer'), action('Enter purchase', { to: 'S02' }), action('Redeem a reward', { to: 'S03' })] },
  ] },
  { id: 'S02', title: 'Record a purchase', role: 'cashier', routes: ['/staff/[businessId]/checkout'], description: 'Review every effect before confirming the purchase.', tables: ['purchases', 'ledger_entries', 'balances', 'offer_claims'], operations: ['preview purchase', 'commit purchase'], sections: [
    { title: 'Customer and branch', readouts: ['Customer display name', 'Cafe', 'Current units', 'Authorized branch'], notes: ['Only available after authorized lookup. Changing branch revalidates permissions and the customer context.'], actions: [action('Change branch', { to: 'S01' })] },
    { title: 'Purchase details', fields: [moneyField('bill', 'Bill total paid (Rs)'), moneyField('eligible', 'Eligible spend (Rs)'), f('receipt', 'Receipt reference', { max: 80 }), select('mode', 'Programme type', ['Stamps', 'Points'], 'Stamps'), { ...check('qualifying', 'Qualifying purchase confirmed'), required: true, when: when('mode', 'Stamps') }, select('claim', 'Associated claimed offer', ['None', 'Discount', 'Treat'], 'None'), { ...moneyField('beforeDiscount', 'Eligible goods before this offer (Rs)'), when: when('claim', 'Discount') }, { ...check('discountApplied', 'I applied the discount in the cafe’s payment process'), required: true, when: when('claim', 'Discount') }, { ...f('claimIntent', 'Active customer offer intent code', { kind: 'code', required: true, min: 8, max: 8 }), when: when('claim', 'Discount', 'Treat') }], notes: ['Enter the actual paid bill after discounts. Eligible spend excludes tax, tips and excluded items. The app does not charge customers or alter a POS bill.'], actions: [action('Use bill amount', { confirm: 'Confirm the entire paid bill is eligible, excluding tax, tips and excluded items.' }), action('Review purchase', { validate: true, confirm: 'Review the server-calculated base award, promotion, referral, offer effect and resulting balance before confirming. This fixture cannot award units.' })] },
    { title: 'Award preview', readouts: ['Base units', 'Double-slot bonus and promotion', 'Member referral bonus', 'Inviter credit summary', 'Applied discount', 'Validated intent countdown', 'Exhausted cap', 'Resulting balance'], notes: ['A changed preview requires another confirmation. After an uncertain timeout, check the original request before retrying.'], actions: [action('Confirm and award'), action('Redeem a reward', { to: 'S03' })] },
    { title: 'Committed receipt', readouts: ['Receipt reference', 'Units granted', 'Balance'], actions: [action('Scan next customer', { to: 'S01' })] },
  ] },
  { id: 'S03', title: 'Fulfill a reward or offer', role: 'cashier', routes: ['/staff/[businessId]/redeem'], description: 'Scan the customer’s active intent. An earning QR is insufficient.', tables: ['redemption_intents', 'offer_claim_intents', 'redemptions', 'offer_claims'], operations: ['resolve intent', 'finalize reward/offer'], sections: [
    { title: 'Customer authorization', fields: [f('intentCode', 'Eight-character intent code', { kind: 'code', required: true, min: 8, max: 8 })], actions: [save('Validate intent')] },
    { title: 'Physical benefit and digital effect', readouts: ['Authorized customer', 'Reward or offer', 'Branch', 'Expiry', 'Current balance', 'Units to deduct', 'Linked validated purchase'], notes: ['Spend-dependent offers require a validated purchase. A treat with no minimum can be fulfilled without a bill. If conditions change, request a fresh preview.'], actions: [action('Confirm reward given', { confirm: 'Confirm you are giving the described reward. The stated units are deducted only after the server commits.' }), action('Confirm offer applied', { confirm: 'Confirm the described offer was physically applied. The active customer intent and all purchase conditions must still be valid.' }), action('Open purchase', { to: 'S02' })] },
  ] },
  { id: 'S04', title: 'Recent activity', role: 'cashier', routes: ['/staff/[businessId]/activity', '/staff/[businessId]/transactions/[id]'], description: 'Cashiers see their own permitted transactions; managers see assigned branches.', report: true, tables: ['purchases', 'redemptions', 'ledger_entries', 'purchase_reversals', 'redemption_reversals'], operations: ['scoped activity', 'reverse purchase', 'undo unfulfilled redemption'], sections: [
    { title: 'Transactions', fields: [select('type', 'Transaction type', ['All', 'Purchase', 'Redemption', 'Reversal'], 'All')], columns: ['Time', 'Reference', 'Customer', 'Type', 'Recorded amount', 'Signed units', 'Status', 'Staff'], empty: 'No transactions in this range. Use Scan to record your first purchase.' },
    { title: 'Transaction detail', readouts: ['Original inputs', 'Programme and promotion versions', 'Referral effects', 'Ledger entries', 'Linked fulfillment', 'Reversal history'] },
    { title: 'Correct a mistake', roles: ['owner', 'manager'], capability: 'reversals', fields: [reason()], notes: ['Full reversals only. Original entries stay in history. Related referral credits are compensated once and may cause a negative balance.'], actions: [action('Reverse purchase', { validate: true, confirm: 'Reverse this entire purchase and its linked earning/referral effects? Any fulfilled offer remains used.' }), action('Undo unfulfilled redemption', { validate: true, confirm: 'Confirm the physical reward was not given. Restore exactly the original debit once.' })] },
  ] },
  { id: 'O01', title: 'Set up your cafe', role: 'owner', routes: ['/dashboard/onboarding'], description: 'Create your business, programme and first reward.', tables: ['businesses', 'branches', 'business_users', 'subscriptions', 'programme_versions', 'reward_versions'], operations: ['bootstrap business', 'save drafts', 'publish programme'], sections: [
    { title: '1 · Business', fields: [select('plan', 'Published plan', ['Sample plan · fixture only'], undefined), ...branding.fields!.map(field => field.kind === 'file' ? { ...field, disabled: 'Save branch details first.' } : field)], notes: ['The sample plan is a local layout fixture, not a subscription. No real published plan is configured. Contact support before starting a trial. Your trial begins when business and branch setup is saved atomically.'] },
    { ...branchDetails, title: '2 · Branch' }, { ...programme, title: '3 · Programme', actions: [] }, { ...reward, title: '4 · Reward', actions: [] }, { ...staff, title: '5 · Staff (optional)', fields: staff.fields!.map(field => field.id === 'branches' ? { ...field, id: 'staffBranches' } : field), actions: [] },
    { title: '6 · Preview and publish', readouts: ['Card preview', 'Public QR', 'Customer journey', 'Completeness checklist'], notes: ['Publication requires a valid plan, branch, programme, reward, accepted assets, current policies and MFA. Test transactions belong only in the separate sandbox.'], actions: [action('Publish programme'), action('Download QR stand')] },
  ] },
  { id: 'O02', title: 'Overview', role: 'manager', routes: ['/dashboard/[businessId]'], description: 'Understand activity recorded through loyalty.', report: true, tables: ['memberships', 'purchases', 'redemptions', 'balances', 'campaigns', 'invoices'], operations: ['overview report'], sections: [
    { title: 'At a glance', readouts: ['New members', 'Purchasing members', 'Returning share', 'Recorded loyalty sales', 'Rewards fulfilled', 'Outstanding units', 'Push-enabled members'], notes: ['Recorded loyalty sales are not total restaurant revenue. Returning share is N/A when the denominator is zero.'] },
    { title: 'Daily activity', columns: ['Date', 'Net recorded loyalty sales', 'Qualifying purchases'], empty: 'No report data loaded. Connect reporting to see the trend.' },
    { title: 'Next actions', actions: [action('Open scanner', { to: 'S01' }), action('Create campaign', { to: 'O10', capability: 'campaigns' }), action('Schedule double stamps/points', { to: 'O07' }), action('Download signup QR', { to: 'O18', roles: ['owner'] })], columns: ['Issue', 'Due', 'Action'], empty: 'Setup tasks, expiring offers, failed campaigns, due invoices and reversal warnings appear here once recorded.', notes: ['Three or more purchase reversals by a staff user in one local day prompt review, not an automatic fraud finding.'] },
  ] },
  { id: 'O03', title: 'Customers', role: 'manager', routes: ['/dashboard/[businessId]/customers'], description: 'Relationships with this cafe, within your branch scope.', tables: ['memberships', 'balances', 'purchases', 'consent_preferences'], operations: ['scoped customer list', 'contact export'], sections: [
    { title: 'Find customers', fields: [f('search', 'Search display name'), select('status', 'Membership status', ['All', 'Active', 'Left', 'Suspended', 'Anonymized'], 'All'), select('activity', 'Activity', ['All', 'Purchased', 'Never purchased', 'Inactive'], 'All'), branch(), check('ready', 'Reward ready'), select('pushConsent', 'Push consent', ['Any', 'Allowed', 'Not allowed'], 'Any'), select('whatsappConsent', 'WhatsApp consent', ['Any', 'Allowed', 'Not allowed'], 'Any')], columns: ['Name', 'Joined', 'Last qualifying purchase', 'Units', 'Purchase count', 'Recorded spend', 'Channel eligibility', 'Status'], empty: 'No customers yet. Share your public signup QR to invite people to join.', actions: [action('View customer', { to: 'O04' })] },
    { title: 'Contact tools', capability: 'contacts', fields: [f('contactSearch', 'Search shared contact')], notes: ['Contact searches are rate limited and audited. A follow-up creates a draft, never sends messages.'], actions: [action('Create follow-up', { to: 'O13' }), action('Export contacts', { capability: 'exports', confirm: 'Export only authorized shared contacts for the selected branches? This requires both contact and export permissions and is audited.' })] },
  ] },
  { id: 'O04', title: 'Customer detail', role: 'manager', routes: ['/dashboard/[businessId]/customers/[membershipId]'], description: 'This cafe’s relationship and scoped activity.', tabs: ['Transactions', 'Rewards', 'Referrals', 'Communication history'], tables: ['memberships', 'membership_contacts', 'consent_preferences', 'adjustments'], operations: ['scoped member detail', 'adjust units', 'record opt-out', 'suspend/reactivate membership'], sections: [
    { title: 'Membership summary', readouts: ['Shared display name', 'Join branch and date', 'Units', 'Latest activity', 'Next reward', 'Referral status and bonus amounts'] },
    { title: 'Shared contacts', capability: 'contacts', readouts: ['Disclosed email', 'WhatsApp number', 'Verification status', 'Channel consent and changed time'], fields: [reason(), check('chatAttestation', 'I confirmed a customer-initiated chat')], notes: ['No global account email, birthday or competitor history. Staff can record opt-out, never opt a customer in.'], actions: [action('Create manual follow-up', { to: 'O13' }), action('Record WhatsApp opt-out', { validate: true, confirm: 'Record this customer’s opt-out and suppress pending tasks immediately?' }), save('Confirm number from customer-initiated chat')] },
    { title: 'Owner controls', roles: ['owner'], fields: [integer('adjustment', 'Signed unit adjustment', -100000, 100000), { ...reason(), id: 'adjustmentReason' }], readouts: ['Resulting balance'], notes: ['Nonzero units only. Normal negative adjustments cannot create debt. Adjustments of at least 1,000 units require reauthentication within 15 minutes.'], actions: [action('Adjust units', { validate: true, confirm: 'Review the signed adjustment and resulting balance. This adds an audited entry; it does not edit history.' }), action('Suspend membership', { validate: true, confirm: 'Suspend participation and marketing with this reason? Retain history and balance.' }), action('Reactivate membership', { validate: true, confirm: 'Reactivate this membership? Previous marketing consent is not silently restored.' })] },
  ] },
  { id: 'O05', title: 'Programme', role: 'owner', routes: ['/dashboard/[businessId]/programme'], description: 'Clear earning rules, preserved history.', tables: ['loyalty_programmes', 'programme_versions'], operations: ['save/publish programme version', 'pause/resume earning'], sections: [programme] },
  { id: 'O06', title: 'Rewards', role: 'owner', routes: ['/dashboard/[businessId]/rewards', '/dashboard/[businessId]/rewards/new', '/dashboard/[businessId]/rewards/[id]'], description: 'Benefits your regulars can work towards.', tables: ['rewards', 'reward_versions', 'reward_branches'], operations: ['save/publish reward'], sections: [{ title: 'Published and draft rewards', columns: ['Title', 'Required units', 'Programme', 'Branches', 'Publication status', 'Fulfillments'], empty: 'Add your first reward with clear terms.', actions: [action('Add reward'), action('View reward'), action('Edit draft')] }, reward] },
  { id: 'O07', title: 'Double slots', role: 'manager', routes: ['/dashboard/[businessId]/promotions', '/dashboard/[businessId]/promotions/[id]'], description: 'Schedule double stamps or points in your assigned branches.', tables: ['earning_promotions', 'promotion_versions', 'promotion_branches'], operations: ['save/publish/pause promotion'], sections: [
    { title: 'Schedule', fields: [select('view', 'Schedule view', ['List', 'Calendar'], 'List')], columns: ['Name', 'Dates', 'Weekdays', 'Local times', 'Branches', 'Status', 'Purchases', 'Bonus units'], empty: 'Create a slot to encourage visits during a quieter time.', actions: [action('Create slot')] },
    { title: 'Slot editor', fields: [required('promotionName', 'Promotion name', 2, 80), branches(), f('startDate', 'Start date', { kind: 'date', required: true }), f('endDate', 'End date', { kind: 'date', required: true }), f('weekdays', 'Weekdays', { kind: 'multi', required: true, options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] }), f('startTime', 'Start time', { kind: 'time', required: true }), f('endTime', 'End time', { kind: 'time', required: true }), moneyField('minimumSpend', 'Minimum eligible spend (Rs)', '0'), { ...integer('dailyCap', 'Max uses per member per day', 1, 100), required: false, help: 'Blank means no per-day cap.' }, integer('bonusCap', 'Maximum bonus units per purchase', 1, 100000, '1000')], readouts: ['Multiplier: 2×', 'Timezone: Asia/Karachi', 'Schedule summary', 'Conflicting slot and branch'], notes: ['Same-day windows only; split overnight slots. Date range is at most 366 days. No overlapping enabled slots on a shared branch. Only base earning is doubled, up to the bonus cap. Historical awards never change.'], actions: [save(), save('Enable slot'), action('Pause', { confirm: 'Pause this slot for future purchases?' })] },
    { title: 'Example earning', fields: [{ ...moneyField('sampleSpend', 'Example eligible spend (Rs)', '250'), required: false }], readouts: ['Base units', 'Bonus units', 'Total', 'Cap effect'], notes: ['Sample points programme: Rs 100 per point gives 2 base + 2 bonus = 4 points for Rs 250, when all conditions pass. Preview is non-binding.'] },
  ] },
  { id: 'O08', title: 'Referrals', role: 'owner', routes: ['/dashboard/[businessId]/referrals'], description: 'Reward the first qualifying purchase, not just a signup.', tabs: ['Rules', 'Results'], report: true, tables: ['referral_rule_versions', 'referral_claims'], operations: ['publish referral rules', 'referral results'], sections: [
    { title: 'Rules', fields: [check('enabled', 'Enable referrals'), integer('inviterBonus', 'Inviter bonus units', 1, 1000), integer('friendBonus', 'Friend bonus units', 1, 1000), moneyField('minimumSpend', 'Minimum qualifying spend (Rs)'), integer('monthlyCap', 'Inviter monthly cap', 1, 1000, '10'), integer('attributionDays', 'Attribution days', 1, 30, '7'), integer('qualificationDays', 'Qualification days', 1, 90, '30')], notes: ['Existing and self referrals are excluded. Friend benefits remain when the inviter cap is reached. Full reversal reverses both awards. Existing claims retain the rules captured when they enrolled.'], readouts: ['Version', 'Effective time'], actions: [save('Save new rules'), action('Pause new referrals', { confirm: 'Pause new referrals? Existing valid claims retain their agreed qualification rules.' })] },
    { title: 'Results', fields: [select('referralStatus', 'Referral status', ['All', 'Pending', 'Qualified', 'Expired', 'Reversed'], 'All')], readouts: ['Signup claims', 'Qualified', 'Expired', 'Reversed', 'Inviter units', 'Friend units'], columns: ['Enrollment', 'Limited party identifiers', 'Qualifying receipt', 'Status', 'Awarded units', 'Suppression reason'], empty: 'No referral results in this range.' },
  ] },
];

export const communicationNote = policy.caps;
