export const screenStates = {
  ready: ['Ready', 'Review the screen below. Sample values are not live records.'],
  loading: ['Loading', 'Loading current data. Previous results are cleared.'],
  empty: ['Nothing here yet', 'Create the first record or use the main action below to get started.'],
  error: ['Could not load this page', 'Your input is preserved. Retry the read when the service is available.'],
  forbidden: ['Access unavailable', 'Your role or branch access does not permit this operation. Return to your workspace.'],
  offline: ['You are offline', 'Reconnect to look up a customer, award units, claim an offer or generate a code. Cached card summaries are stale.'],
  expired: ['Code expired', 'No units have been deducted. Revalidate the current balance before generating a new code.'],
  stale: ['Balance or rules changed', 'Review the latest server preview and confirm again. Nothing was written using the stale preview.'],
  invalid: ['Invalid QR', 'Check that this is the correct cafe and code type. No customer details are shown before validation.'],
  processed: ['Already processed', 'Retrieve the original committed receipt using the same request key. Do not create another transaction.'],
  revoked: ['Staff access revoked', 'The next operation is blocked. Contact the business owner and return to your workspace.'],
  limited: ['Please wait before retrying', 'This action is rate limited. Follow the server retry time rather than repeatedly submitting.'],
  paused: ['Participation paused', 'New participation is unavailable. Existing balance and history remain subject to the access policy.'],
  provider: ['Provider unavailable', 'The external service could not complete the request. No success is being claimed.'],
  denied: ['Notifications denied', 'You can still use loyalty. Enable permission in browser settings only if you want notifications.'],
  unsupported: ['Notifications unsupported', 'Loyalty and the inbox remain available. Supported iPhone push requires installing the app first.'],
  uncertain: ['Result not yet known', 'Keep the same request key. Check its status before retrying; do not submit a new transaction.'],
  committed: ['Committed receipt layout', 'This is a design-state illustration only. Live success must show the server receipt, timestamp and committed balance.'],
  emailSent: ['Check your email', 'If this address can receive a sign-in link, it will arrive shortly. This is a layout fixture; no email was sent.'],
  cooldown: ['Resend available shortly', 'Wait for the server-provided cooldown before requesting another sign-in link.'],
  installation: ['Install for notifications', 'On a supported iPhone, add the app to your Home Screen and open it there before enabling push. Installation is optional for loyalty.'],
  zeroAudience: ['No eligible recipients', 'The scan completed with zero consent-eligible members. No message is queued and no retry is needed.'],
  uploading: ['Uploading image', 'The private upload must finish before processing. This preview does not upload files.'],
  processing: ['Processing image', 'The image must pass server decoding and validation before publication.'],
  rejected: ['Image rejected', 'Use a JPEG, PNG or WebP image within the size and dimension limits. The original will not be publicly served.'],
} as const;
export type ScreenState = keyof typeof screenStates;
