import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import pg from 'pg';
import {processPrivacy,ACCOUNT_PART_BYTES} from '../src/worker/privacy.ts';
import {openSecret} from '../src/lib/security/crypto.ts';
import {purgeReportExports} from '../src/worker/report-export.ts';
export async function testPhase8({client,postgres,test,password,port}){
 const people=[];
 for(const role of ['owner','admin','billingOnly','supportOnly','member','other']){const p={id:randomUUID(),session:randomUUID(),role};people.push(p);await client.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[p.id,`phase8-${role}@example.invalid`]);await client.query('insert into auth.sessions(id,user_id) values($1,$2)',[p.session,p.id]);await client.query("insert into public.profiles(user_id,auth_user_id,display_name,birthday_month,birthday_day) values($1,$1,$2,2,29)",[p.id,`TEST ${role}`]);if(['admin','billingOnly','supportOnly'].includes(role))await client.query('insert into public.platform_admins(user_id,active,can_reconcile_billing,can_manage_support) values($1,true,$2,$3)',[p.id,role!=='supportOnly',role!=='billingOnly']);}
 const [owner,admin,billingOnly,supportOnly,member,other]=people;
 const rpc=async(who,name,args=[],conn=client,aal='aal2',fresh=true)=>{await conn.query('begin');try{await conn.query('set local role authenticated');await conn.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claims',$2,true)",[who.id,JSON.stringify({sub:who.id,session_id:who.session,aal,amr:[{method:'totp',timestamp:Math.floor(Date.now()/1000)-(fresh?0:3600)}]})]);const result=(await conn.query(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')}) result`,args)).rows[0].result;await conn.query('commit');return result;}catch(e){await conn.query('rollback');throw e;}};
 const cafe=randomUUID(),branch=randomUUID(),membership=randomUUID(),otherMembership=randomUUID(),programme=randomUUID(),version=randomUUID();
 await client.query('begin');await client.query("insert into public.businesses(id,slug,display_name,status,created_by) values($1,'phase8-billing-fixture','TEST Phase8 cafe','active',$2)",[cafe,owner.id]);await client.query("insert into public.business_users(business_id,user_id,staff_display_name,staff_email,role) values($1,$2,'TEST owner','phase8-owner@example.invalid','owner')",[cafe,owner.id]);await client.query("insert into public.branches(id,business_id,name,address,city) values($1,$2,'TEST branch','TEST fictional address','Lahore')",[branch,cafe]);await client.query('commit');
 const price='550050';const published=await rpc(admin,'save_plan_version',[{code:'test-phase8',name:'TEST billing plan',active:true,pricePaisa:price,billingPeriod:'monthly',branchLimit:1,staffLimit:2,memberLimit:10000,monthlyCampaignLimit:10,trialDays:14},true,randomUUID()]);
 // Just-ended trial, current interval and next anchored interval for out-of-order coverage.
 await client.query("insert into public.subscriptions(business_id,plan_version_id,status,period_start,period_end,billing_anchor_at) values($1,$2,'trial',now()-interval '15 days',now()-interval '1 day',now()-interval '15 days')",[cafe,published.id]);
 await client.query("insert into public.loyalty_programmes(id,business_id,type,status,name) values($1,$2,'stamps','published','TEST stamps')",[programme,cafe]);await client.query("insert into public.programme_versions(id,business_id,programme_id,version,status,effective_at,published_at,minimum_spend_paisa,stamps_per_purchase,max_base_units_per_purchase,terms,created_by) values($1,$2,$3,1,'published',now()-interval '1 day',now()-interval '1 day',0,1,10,'TEST one stamp per purchase',$4)",[version,cafe,programme,owner.id]);
 for(const [m,p,name]of [[membership,member,'TEST member'],[otherMembership,other,'OTHER CUSTOMER SECRET']]){await client.query('insert into public.memberships(id,business_id,customer_user_id,display_name,joined_branch_id) values($1,$2,$3,$4,$5)',[m,cafe,p.id,name,branch]);await client.query('insert into public.balances(business_id,membership_id,units) values($1,$2,17)',[cafe,m]);await client.query("insert into public.membership_contacts(business_id,membership_id,phone_e164,shared_email) values($1,$2,'+923001234567',$3)",[cafe,m,`phase8-${p.role}@example.invalid`]);}
 const pool=new pg.Pool({connectionString:`postgresql://integration_worker:${password}@127.0.0.1:${port}/postgres`,max:2});
 const encryption={id:'phase8-test',bytes:randomBytes(32)},files=new Map(),storage={key:encryption,async put(path,bytes){files.set(path,bytes);},async sign(path){return `https://storage.example.invalid/${path}?token=fixture`;},async remove(path){files.delete(path);}};
 try{
 await test('Phase 8 calendar periods retain original Jan31/leap-day anchor for monthly and annual billing',async()=>{
  const boundaries=(await client.query("select app_private.billing_boundary('2024-01-31T05:00Z','monthly',1) feb,app_private.billing_boundary('2024-01-31T05:00Z','monthly',2) mar,app_private.billing_boundary('2024-02-29T05:00Z','annual',1) annual,app_private.billing_boundary('2024-02-29T05:00Z','annual',4) leap")).rows[0];assert.equal(boundaries.feb.toISOString(),'2024-02-29T05:00:00.000Z');assert.equal(boundaries.mar.toISOString(),'2024-03-31T05:00:00.000Z');assert.equal(boundaries.annual.toISOString(),'2025-02-28T05:00:00.000Z');assert.equal(boundaries.leap.toISOString(),'2028-02-29T05:00:00.000Z');
 });
 await test('Phase 8 plans are immutable positive-priced configuration with exact admin capabilities and MFA',async()=>{
  await assert.rejects(rpc(owner,'admin_read',['overview',{}]),{code:'42501'});await assert.rejects(rpc(admin,'admin_read',['overview',{}],client,'aal1'),{code:'42501'});await assert.rejects(rpc(supportOnly,'save_plan_version',[{code:'bad-zero',name:'TEST zero',active:true,pricePaisa:'0',billingPeriod:'monthly',branchLimit:1,staffLimit:1,trialDays:14},true,randomUUID()]),{code:'42501'});
  await assert.rejects(rpc(billingOnly,'save_plan_version',[{code:'bad-zero',name:'TEST zero',active:true,pricePaisa:'0',billingPeriod:'monthly',branchLimit:1,staffLimit:1,trialDays:14},true,randomUUID()]),{code:'23514'});assert((await rpc(billingOnly,'admin_read',['billing',{}])).rows);
  await assert.rejects(client.query('update public.plan_versions set price_paisa=1 where id=$1',[published.id]),{code:'42501'});
 });
 await test('Phase 8 scheduled billing issues anchored invoices once, seven days before renewal, with frozen price snapshots',async()=>{
  await pool.query('select public.worker_billing_cycle()');await pool.query('select public.worker_billing_cycle()');assert.equal((await client.query('select count(*) from public.invoices where business_id=$1',[cafe])).rows[0].count,'1');
  const s=(await client.query('select * from public.subscriptions where business_id=$1',[cafe])).rows[0];const nextStart=(await client.query('select app_private.billing_boundary($1,\'monthly\',1) at',[s.billing_anchor_at])).rows[0].at;
  await client.query("select app_private.issue_invoices($1,app_private.billing_boundary((select billing_anchor_at from public.subscriptions where business_id=$1),'monthly',1)-interval '7 days')",[cafe]);assert.equal((await client.query('select count(*) from public.invoices where business_id=$1',[cafe])).rows[0].count,'2');assert(nextStart);
  await assert.rejects(client.query('update public.invoices set amount_paisa=1 where business_id=$1',[cafe]),{code:'42501'});
 });
 const invoices=(await client.query('select * from public.invoices where business_id=$1 order by period_start',[cafe])).rows;const [first,next]=invoices;
 let submission,key= randomUUID(),payment;
 const confirm=(invoice,ref,extra={})=>[invoice.id,{verifiedAmountPaisa:price,method:'bank_transfer',provider:'test-bank',reference:ref,decision:'confirm',reconciled:true,...extra},randomUUID(),randomUUID()];
 await rpc(admin,'update_platform_setting',['canonical_providers',JSON.stringify(['test-bank']),'TEST canonical staging bank identifier',randomUUID()]);
 await test('Phase 8 owner payment evidence and validated screenshot cannot settle an invoice or change access',async()=>{
  const asset=randomUUID();await client.query("insert into public.media_assets(id,business_id,storage_path,kind,mime_type,bytes,width,height,uploaded_by,validation_status,visibility) values($1,$2,$3,'payment_proof','image/webp',100,10,10,$4,'accepted','private')",[asset,cafe,`${cafe}/${asset}/v1.webp`,owner.id]);
  const input={claimedAmountPaisa:price,method:'bank_transfer',reference:'TEST screenshot claim',proofAssetId:asset};submission=await rpc(owner,'submit_payment_evidence',[cafe,first.id,input,key,randomUUID()]);assert.equal(submission.status,'pending_review');assert.equal((await rpc(owner,'submit_payment_evidence',[cafe,first.id,input,key,randomUUID()])).submissionId,submission.submissionId);
  assert.equal((await client.query('select status from public.invoices where id=$1',[first.id])).rows[0].status,'overdue');assert.equal((await client.query('select count(*) from public.payment_events where business_id=$1',[cafe])).rows[0].count,'0');
  await assert.rejects(rpc(member,'billing_view',[cafe]),{code:'42501'});await assert.rejects(rpc(other,'submit_payment_evidence',[cafe,first.id,input,randomUUID(),randomUUID()]),{code:'42501'});assert((await rpc(admin,'payment_proof_access',[asset,randomUUID()])).path.endsWith('v1.webp'));await assert.rejects(rpc(supportOnly,'payment_proof_access',[asset,randomUUID()]),{code:'42501'});
 });
 await test('Phase 8 reconciliation rejects partial payment, missing bank attestation, unconfigured provider and stale MFA',async()=>{
  for(const extra of [{verifiedAmountPaisa:'550000'},{reconciled:false},{provider:'fabricated-bank'}])await assert.rejects(rpc(admin,'reconcile_payment',confirm(first,'TEST invalid',extra)),{code:'22023'});
  await assert.rejects(rpc(admin,'reconcile_payment',confirm(first,'TEST stale'),client,'aal2',false),{code:'42501'});await assert.rejects(rpc(supportOnly,'reconcile_payment',confirm(first,'TEST role')),{code:'42501'});
 });
 await test('Phase 8 concurrent confirmation and idempotent retries produce one full payment and one coverage interval',async()=>{
  const args=confirm(first,'  TEST-CONCURRENT-REF  ',{submissionId:submission.submissionId});
  const results=await Promise.all(Array.from({length:5},async()=>{const c=postgres.getPgClient();await c.connect();try{return await rpc(admin,'reconcile_payment',args,c);}finally{await c.end();}}));assert(results.every(r=>r.paymentEventId===results[0].paymentEventId));payment=results[0].paymentEventId;
  assert.equal((await client.query('select count(*) from public.payment_events where invoice_id=$1',[first.id])).rows[0].count,'1');assert.equal((await rpc(owner,'billing_view',[cafe])).subscription.status,'active');assert.equal((await client.query('select period_end from public.subscriptions where business_id=$1',[cafe])).rows[0].period_end.toISOString(),first.period_end.toISOString());
  await assert.rejects(rpc(admin,'reconcile_payment',confirm(first,'different-reference')),{code:'22023'});
 });
 await test('Phase 8 explicit paid-compatible plan downgrade preserves history, verifies billing and audits the change',async()=>{
 const v=await rpc(admin,'save_plan_version',[{code:'test-phase8-limits',name:'TEST lower limits',active:true,pricePaisa:price,billingPeriod:'monthly',branchLimit:1,staffLimit:1,memberLimit:1,monthlyCampaignLimit:1,trialDays:0},true,randomUUID()]);
 await assert.rejects(rpc(supportOnly,'admin_change_plan',[cafe,v.id,first.id,'TEST unauthorized plan change attempt',randomUUID()]),{code:'42501'});
 await rpc(admin,'admin_change_plan',[cafe,v.id,first.id,'TEST exact paid price lower limits change',randomUUID()]);assert.equal((await rpc(owner,'billing_view',[cafe])).subscription.limits.members,1);assert.equal((await client.query('select sum(units) units from public.balances where business_id=$1',[cafe])).rows[0].units,'34');assert.equal((await client.query("select count(*) from public.audit_events where business_id=$1 and action='subscription.plan_changed'",[cafe])).rows[0].count,'1');
 });
 let futurePayment;
 await test('Phase 8 normalized confirmed bank references are globally unique and future payment cannot extend current interval twice',async()=>{
  await assert.rejects(rpc(admin,'reconcile_payment',confirm(next,'test-concurrent-ref')),{code:'23505'});
  futurePayment=(await rpc(billingOnly,'reconcile_payment',confirm(next,'TEST-future-ref'))).paymentEventId;assert.equal((await client.query('select period_end from public.subscriptions where business_id=$1',[cafe])).rows[0].period_end.toISOString(),first.period_end.toISOString());assert.equal((await rpc(owner,'billing_view',[cafe])).subscription.status,'active');
 });
 await test('Phase 8 correction appends original positive amount once, reopens exact invoice and preserves later valid payment',async()=>{
  const args=[payment,'TEST bank verification was incorrect',randomUUID(),randomUUID()];const corrected=await rpc(admin,'correct_payment',args);assert.equal((await rpc(admin,'correct_payment',args)).paymentEventId,corrected.paymentEventId);await assert.rejects(rpc(admin,'correct_payment',[payment,'TEST second correction should be denied',randomUUID(),randomUUID()]),{code:'23505'});
  const events=(await client.query('select event,verified_amount_paisa from public.payment_events where invoice_id=$1 order by created_at',[first.id])).rows;assert.deepEqual(events.map(e=>e.event),['confirmed','correction']);assert(events.every(e=>e.verified_amount_paisa===price));assert.equal((await client.query('select status from public.invoices where id=$1',[next.id])).rows[0].status,'paid');assert.equal((await client.query('select count(*) from public.payment_events where id=$1',[futurePayment])).rows[0].count,'1');
  assert.equal((await client.query('select app_private.subscription_state($1,(select period_start from public.invoices where id=$2)) s',[cafe,next.id])).rows[0].s,'active');await rpc(admin,'reconcile_payment',confirm(first,'TEST-verified-replacement'));
 });
 await test('Phase 8 suspension, reinstatement and cancellation preserve balances and enforce effective access without scheduler',async()=>{
  const balances=(await client.query('select membership_id,units from public.balances where business_id=$1 order by membership_id',[cafe])).rows;
  await rpc(admin,'admin_tenant_action',[cafe,'suspend','TEST deliberate subscription suspension',randomUUID()]);assert.equal((await client.query('select app_private.entitled($1) entitled',[cafe])).rows[0].entitled,false);assert((await rpc(owner,'billing_view',[cafe])).invoices.length);
  await pool.query('select public.worker_billing_cycle()');assert.equal((await rpc(owner,'billing_view',[cafe])).subscription.status,'suspended');await rpc(admin,'admin_tenant_action',[cafe,'reinstate','TEST restore independently paid access',randomUUID()]);assert.equal((await rpc(owner,'billing_view',[cafe])).subscription.status,'active');
  await rpc(owner,'cancel_subscription_renewal',[cafe,randomUUID()]);assert.equal((await client.query('select app_private.subscription_state($1,(select period_end from public.invoices where id=$2)) s',[cafe,first.id])).rows[0].s,'canceled');assert.deepEqual((await client.query('select membership_id,units from public.balances where business_id=$1 order by membership_id',[cafe])).rows,balances);
 });
 await test('Phase 8 exact invoice detail is available beyond the first 100 admin rows',async()=>{
 await client.query("insert into public.invoices(business_id,subscription_id,plan_version_id,reference,amount_paisa,period_start,period_end,due_at,issued_at,status) select business_id,id,plan_version_id,'TEST-OLD-'||n,550050,billing_anchor_at-make_interval(months=>n),billing_anchor_at-make_interval(months=>n-1),billing_anchor_at-make_interval(months=>n),now(),'overdue' from public.subscriptions cross join generate_series(2,106) n where business_id=$1",[cafe]);assert(!(await rpc(admin,'admin_read',['billing',{businessId:cafe,pageSize:100}])).rows.some(i=>i.id===first.id));assert.equal((await rpc(admin,'admin_invoice_view',[first.id])).rows[0].id,first.id);
 });
 let grant;
 await test('Phase 8 audited support is scope/time/admin bound, contains no customer contacts, and ends immediately',async()=>{
  await assert.rejects(rpc(billingOnly,'start_support_access',[cafe,'TEST support access attempt','configuration',15,randomUUID()]),{code:'42501'});await assert.rejects(rpc(admin,'start_support_access',[cafe,'TEST stale support authentication','configuration',15,randomUUID()],client,'aal2',false),{code:'42501'});
  grant=await rpc(admin,'start_support_access',[cafe,'TEST inspect programme configuration','configuration',15,randomUUID()]);const result=await rpc(admin,'support_read',[grant.grantId,randomUUID()]);assert.equal(result.programme.name,'TEST stamps');assert(!JSON.stringify(result).includes('phone'));
  await assert.rejects(rpc(supportOnly,'support_read',[grant.grantId,randomUUID()]),{code:'42501'});await rpc(admin,'end_support_access',[grant.grantId,randomUUID()]);await assert.rejects(rpc(admin,'support_read',[grant.grantId,randomUUID()]),{code:'42501'});assert.equal((await client.query('select count(*) from public.audit_events where support_access_grant_id=$1',[grant.grantId])).rows[0].count,'3');
 });
 await test('Phase 8 admin read/revocation and raw tables/worker routines stay closed to ordinary clients',async()=>{
  assert((await rpc(admin,'admin_read',['jobs',{}])).rows);assert((await rpc(admin,'admin_read',['audit',{businessId:cafe}])).rows.length>0);
  await assert.rejects(rpc(admin,'admin_read',['audit',{pageSize:101}]),{code:'22023'});for(const table of ['invoices','payment_events','platform_admins','privacy_requests','support_access_grants']){await client.query('begin');try{await client.query('set local role authenticated');await assert.rejects(client.query(`select * from public.${table}`),{code:'42501'});}finally{await client.query('rollback');}}
  await client.query('update public.platform_admins set active=false where user_id=$1',[supportOnly.id]);await assert.rejects(rpc(supportOnly,'admin_read',['overview',{}]),{code:'42501'});await assert.rejects(rpc(member,'worker_privacy_job',[randomUUID()]),{code:'42501'});
 });
 const eventFor=async id=>(await client.query("select id from public.outbox_events where event_type='privacy.requested' and event_key=$1",[id])).rows[0].id;
 let exported;
 await test('Phase 8 account exports stream more than 10000 records into numbered <=3MiB private parts plus complete manifest',async()=>{
  await client.query(`insert into public.purchases(business_id,branch_id,membership_id,programme_version_id,recorded_bill_paisa,eligible_spend_paisa,base_units,qualifying_purchase_confirmed,qualifies_for_loyalty,occurred_at,staff_user_id,idempotency_key,request_hash) select $1,$2,$3,$4,0,0,0,true,false,now(),$5,gen_random_uuid()::text,repeat('a',64) from generate_series(1,12000)`,[cafe,branch,membership,version,owner.id]);
  const key=randomUUID();exported=await rpc(member,'request_privacy',['export',null,key,randomUUID()]);assert.equal((await rpc(member,'request_privacy',['export',null,key,randomUUID()])).requestId,exported.requestId);
  await processPrivacy(pool,await eventFor(exported.requestId),storage,{remove:async()=>{throw new Error('must_not_delete_export');}});const state=await rpc(member,'my_privacy_requests');const r=state.requests.find(r=>r.id===exported.requestId);assert.equal(r.status,'completed');assert(r.parts.length>=3);assert(r.parts.every(p=>BigInt(p.bytes)<=BigInt(ACCOUNT_PART_BYTES)));
  const artifact=(await client.query('select storage_path from public.export_artifacts where export_request_id=$1 and part_number=1',[r.exportRequestId])).rows[0];const manifest=JSON.parse(files.get(artifact.storage_path));assert.equal(manifest.counts.purchases,12000);assert.equal(manifest.counts.memberships,1);assert.equal(manifest.parts.length,r.parts.length-1);
  const text=[...files.values()].map(b=>b.toString()).join('');assert(!text.includes('OTHER CUSTOMER SECRET'));assert(!text.includes('token_ciphertext'));const access=await rpc(member,'account_export_access',[r.parts[0].id,randomUUID()]);assert(openSecret(access.ciphertext,encryption,`account-export:${r.exportRequestId}:${access.part}`).includes('storage.example.invalid'));
  await assert.rejects(rpc(other,'account_export_access',[r.parts[0].id,randomUUID()]),{code:'42501'});await processPrivacy(pool,await eventFor(exported.requestId),storage,{remove:async()=>{}});assert.equal((await client.query("select count(*) from public.job_effect_receipts where handler_name='privacy.completed' and event_key=$1",[r.id])).rows[0].count,'1');
 });
 await test('Phase 8 account deletion requires recent authentication and blocks active owners without orphaning businesses',async()=>{
  await assert.rejects(rpc(member,'request_privacy',['delete_account',null,randomUUID(),randomUUID()],client,'aal1',false),{code:'42501'});const result=await rpc(owner,'request_privacy',['delete_account',null,randomUUID(),randomUUID()]);assert.equal(result.status,'blocked');assert.equal(result.errorCode,'active_business_owner');assert.equal((await client.query('select status from public.business_users where business_id=$1 and user_id=$2',[cafe,owner.id])).rows[0].status,'active');
 });
 await test('Phase 8 membership deletion clears shared contacts, revokes scanner handles and preserves private link/financial balance',async()=>{
  const rule=randomUUID(),run=randomUUID();await client.query("insert into public.automation_rules(id,business_id,kind,title_template,body_template,inactive_days) values($1,$2,'inactivity','TEST reminder','TEST generic reminder body',30)",[rule,cafe]);await client.query("insert into public.automation_runs(id,business_id,rule_id,rule_version,membership_id,event_key,scheduled_at,expires_at,rendered_title,rendered_body,rule_snapshot) values($1,$2,$3,1,$4,'TEST-delete-content',now(),now()+interval '1 day','OTHER CUSTOMER SECRET','OTHER CUSTOMER SECRET +923001234567','{}')",[run,cafe,rule,otherMembership]);
  const handle=randomUUID();await client.query("insert into public.membership_handles(id,business_id,membership_id,handle_hash,handle_ciphertext,encryption_key_id) values($1,$2,$3,$4,'TEST encrypted handle','TEST')",[handle,cafe,otherMembership,randomBytes(32).toString('hex')]);
  const req=await rpc(other,'request_privacy',['delete_membership',otherMembership,randomUUID(),randomUUID()]);await processPrivacy(pool,await eventFor(req.requestId),storage,{remove:async()=>{throw new Error('membership_not_auth_deletion');}});
  const m=(await client.query('select * from public.memberships where id=$1',[otherMembership])).rows[0];assert.equal(m.status,'anonymized');assert.equal(m.customer_user_id,other.id);assert.equal((await client.query('select phone_e164 from public.membership_contacts where membership_id=$1',[otherMembership])).rows[0].phone_e164,null);assert.equal((await client.query('select units from public.balances where membership_id=$1',[otherMembership])).rows[0].units,'17');assert.equal((await client.query('select status from public.membership_handles where id=$1',[handle])).rows[0].status,'revoked');const scheduled=(await client.query('select state,rendered_title,rendered_body from public.automation_runs where id=$1',[run])).rows[0];assert.equal(scheduled.state,'suppressed');assert(!JSON.stringify(scheduled).includes('OTHER CUSTOMER SECRET'));assert(!JSON.stringify(scheduled).includes('+923001234567'));
 });
 await test('Phase 8 deletion survives Auth provider failure, immediately blocks stale sessions and resumes without losing history',async()=>{
  const req=await rpc(member,'request_privacy',['delete_account',null,randomUUID(),randomUUID()]),event=await eventFor(req.requestId);let attempts=0;await assert.rejects(processPrivacy(pool,event,storage,{remove:async()=>{attempts++;throw new Error('TEST provider down');}}));
  const profile=(await client.query('select * from public.profiles where user_id=$1',[member.id])).rows[0];assert.equal(profile.auth_user_id,null);assert.equal(profile.display_name,'Deleted user');assert.equal(profile.birthday_month,null);assert.equal((await client.query('select customer_user_id from public.memberships where id=$1',[membership])).rows[0].customer_user_id,null);assert.equal((await client.query('select count(*) from public.purchases where membership_id=$1',[membership])).rows[0].count,'12000');assert.equal((await client.query('select units from public.balances where membership_id=$1',[membership])).rows[0].units,'17');await assert.rejects(rpc(member,'my_privacy_requests'),{code:'42501'});
  await rpc(admin,'admin_retry_privacy',[req.requestId,'TEST retry after Auth provider recovery',randomUUID()]);await processPrivacy(pool,event,storage,{remove:async id=>{assert.equal(id,member.id);attempts++;await client.query('delete from auth.users where id=$1',[id]);}});assert.equal(attempts,2);assert.equal((await client.query('select status,auth_identity_id from public.privacy_requests where id=$1',[req.requestId])).rows[0].status,'completed');assert.equal((await client.query('select auth_identity_id from public.privacy_requests where id=$1',[req.requestId])).rows[0].auth_identity_id,null);
 });
 await test('Phase 8 retention erases expired artifact bytes and evidence stays honest without deleting payments or ledger',async()=>{
  await client.query("update public.export_artifacts set expires_at=now()-interval '1 second' where export_request_id=(select export_request_id from public.privacy_requests where id=$1)",[exported.requestId]);await purgeReportExports(pool,storage);assert.equal(files.size,0);const before=(await client.query('select count(*) from public.payment_events')).rows[0].count;await pool.query('select public.worker_retention()');assert.equal((await client.query('select count(*) from public.payment_events')).rows[0].count,before);const health=(await pool.query('select public.worker_health_status() h')).rows[0].h;assert.equal(health.backupStatus,null);
 });
 }finally{await pool.end();}
}
