'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {columns,defaultColumns,filters,kinds,label,report,type Config,type Filters,type Report,type ReportKind} from './contracts';
const DailyChart=dynamic(()=>import('./chart'),{ssr:false,loading:()=> <p>Loading chart…</p>});
const titles:Record<ReportKind,string>={overview:'Overview',customers:'Customers',rewards:'Rewards',referrals:'Referrals',promotions:'Double slots',campaigns:'Campaigns',staff:'Staff'};
const metricLabels:Record<string,string>={recordedSalesPaisa:'Net recorded loyalty sales (Rs)',eligibleSpendPaisa:'Eligible loyalty spend (Rs)',averageBillPaisa:'Average recorded bill (Rs)',returningShare:'Returning purchasing card share (%)',repeatWithinPeriod:'Cards with 2+ qualifying purchases',outstandingUnitsCurrent:'Current outstanding units · all branches',adjustmentDebtCurrent:'Current adjustment debt · all branches',estimatedCostPaisa:'Estimated reward cost (Rs)',knownEstimatedCostPaisa:'Known estimated reward cost (Rs)',manualTasksOpened:'WhatsApp tasks opened',manualTasksStaffMarkedSent:'WhatsApp tasks staff marked sent',uniqueAudience:'Unique audience cards per campaign',visitCoverageStart:'Approximate visit coverage starts'};
function display(value:unknown,key:string){if(value===null||value===undefined)return 'N/A';if(typeof value==='boolean')return value?'Yes':'No';if(key.endsWith('Paisa')){const n=BigInt(String(value)),abs=n<0n?-n:n;return `${n<0n?'-':''}${(abs/100n).toLocaleString('en-PK')}.${String(abs%100n).padStart(2,'0')}`;}return String(value);}
type ExportStatus={exportRequestId:string;status:string;errorCode?:string|null;expiresAt?:string|null;rowCount?:number|null};
export function Reports({businessId,config,overviewOnly=false}:{businessId:string;config:Config;overviewOnly?:boolean}){
 const [kind,setKind]=useState<ReportKind>('overview'),[preset,setPreset]=useState<Filters['preset']>('last30'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[branch,setBranch]=useState(''),[selector,setSelector]=useState(''),[programme,setProgramme]=useState(''),[pageSize,setPageSize]=useState<25|50|100>(25),[sort,setSort]=useState<'default'|'reverse'>('default'),[cursor,setCursor]=useState('0');
 const [storedResult,setResult]=useState<Report|null>(null),[loadedSelection,setLoadedSelection]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const [confirm,setConfirm]=useState(false),[contactExport,setContactExport]=useState(false),[chosen,setChosen]=useState<string[]>(defaultColumns('overview')),[exportState,setExportState]=useState<ExportStatus|null>(null),[exportBusy,setExportBusy]=useState(false),[exportError,setExportError]=useState('');
 const controller=useRef<AbortController|null>(null),inFlight=useRef(false),exportKey=useRef<string|null>(null),dialog=useRef<HTMLDialogElement>(null);
 const selection=JSON.stringify({reportKind:kind,preset,...(preset==='custom'?{startDate:start,endDate:end}:{}),branchIds:branch?[branch]:[],pageSize,sort,cursor,
 ...(programme?{programmeVersionId:programme}:{}),...(selector?{[kind==='rewards'?'rewardVersionId':kind==='promotions'?'promotionId':'campaignId']:selector}:{})});
 const result=loadedSelection===selection?storedResult:null;
 useEffect(()=>{
  const abort=new AbortController();controller.current?.abort();controller.current=abort;setResult(null);setError('');inFlight.current=true;setLoading(true);
  const checked=filters.safeParse(JSON.parse(selection));
  if(!checked.success){setError('Choose a valid date range of 1–90 calendar days.');setLoading(false);inFlight.current=false;return ()=>abort.abort();}
  fetch('/api/reports/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,filters:checked.data}),cache:'no-store',signal:abort.signal})
   .then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error?.message??'Reports could not be loaded. Retry.');return report.parse(value.data);})
   .then(data=>{if(!abort.signal.aborted){setLoadedSelection(selection);setResult(data);}}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Reports could not be loaded. Retry.');})
   .finally(()=>{if(!abort.signal.aborted){inFlight.current=false;setLoading(false);}});
  return ()=>abort.abort();
 },[businessId,selection,refresh]);
 useEffect(()=>{if(confirm&&!dialog.current?.open)dialog.current?.showModal();},[confirm]);
 function changeTab(next:ReportKind){controller.current?.abort();setResult(null);setKind(next);setCursor('0');setSelector('');setProgramme('');setConfirm(false);setExportError('');}
 function rerun(){if(inFlight.current)return;inFlight.current=true;setResult(null);setRefresh(v=>v+1);}
 function beginExport(contacts:boolean){setContactExport(contacts);setChosen(defaultColumns(contacts?'contacts':kind));exportKey.current=crypto.randomUUID();setExportError('');setConfirm(true);}
 async function exportRequest(){if(exportBusy||!result)return;setExportBusy(true);setExportError('');try{
  const v={...JSON.parse(selection),preset:'custom',startDate:result.appliedFilters.startDate,endDate:result.appliedFilters.endDate,cursor:'0',...(contactExport?{reportKind:'contacts',programmeVersionId:undefined,rewardVersionId:undefined,promotionId:undefined,campaignId:undefined}:{})};
  const response=await fetch('/api/reports/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,filters:v,columns:chosen,idempotencyKey:exportKey.current}),cache:'no-store'}),value=await response.json();
  if(!response.ok)throw new Error(value.error?.message??'Export could not be requested. Retry.');setExportState(value.data);setConfirm(false);dialog.current?.close();
 }catch(e){setExportError(e instanceof Error?e.message:'Export failed. Retry.');}finally{setExportBusy(false);}}
 async function checkExport(){if(!exportState||exportBusy)return;setExportBusy(true);setExportError('');try{
  const response=await fetch('/api/reports/export-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,exportRequestId:exportState.exportRequestId}),cache:'no-store'}),value=await response.json();
  if(!response.ok)throw new Error(value.error?.message??'Export status unavailable. Retry.');setExportState(value.data);
 }catch(e){setExportError(e instanceof Error?e.message:'Export unavailable.');}finally{setExportBusy(false);}}
 const options=kind==='rewards'?config.rewards:kind==='promotions'?config.promotions:kind==='campaigns'?config.campaigns:[];
 const exportKind=contactExport?'contacts':kind;
 return <section className="reports-view" aria-label="Loyalty reports"><header className="actions"><div><h1>{overviewOnly?'Loyalty overview':'Reports'}</h1><p>{config.businessName} · {config.timezone}</p></div>{overviewOnly&&<Link className="button button-secondary" href={`/dashboard/${businessId}/reports`}>Open all reports</Link>}</header>
 {!overviewOnly&&<div role="tablist" aria-label="Report tabs" className="actions">{kinds.map((k,i)=><button className="button button-secondary" type="button" key={k} role="tab" id={`tab-${k}`} aria-controls="report-panel" aria-selected={kind===k} tabIndex={kind===k?0:-1} onClick={()=>changeTab(k)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?kinds.length-1:(i+(e.key==='ArrowRight'?1:kinds.length-1))%kinds.length;changeTab(kinds[n]!);document.getElementById(`tab-${kinds[n]}`)?.focus();}}}>{titles[k]}</button>)}</div>}
 <div className="screen-panel report-filters"><label>Date range<select aria-label="Date range" value={preset} onChange={e=>{setPreset(e.target.value as Filters['preset']);setCursor('0');}}><option value="today">Today</option><option value="last7">Last 7 days</option><option value="last30">Last 30 days</option><option value="custom">Custom</option></select></label>
 {preset==='custom'&&<><label>Start date<input type="date" value={start} onChange={e=>{setStart(e.target.value);setCursor('0');}}/></label><label>End date<input type="date" value={end} onChange={e=>{setEnd(e.target.value);setCursor('0');}}/></label></>}
 <label>Branch<select aria-label="Branch" value={branch} onChange={e=>{setBranch(e.target.value);setCursor('0');}}><option value="">{config.role==='owner'?'All branches':'All assigned branches'}</option>{config.branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>
 {['overview','customers','promotions'].includes(kind)&&<label>Programme version<select value={programme} onChange={e=>{setProgramme(e.target.value);setCursor('0');}}><option value="">All versions</option>{config.programmes.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}
 {['rewards','promotions','campaigns'].includes(kind)&&<label>{kind==='rewards'?'Reward':kind==='promotions'?'Double slot':'Campaign'}<select value={selector} onChange={e=>{setSelector(e.target.value);setCursor('0');}}><option value="">All</option>{options.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}
 <label>Rows per page<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value) as 25|50|100);setCursor('0');}}>{[25,50,100].map(n=><option value={n} key={n}>{n}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>{setSort(e.target.value as 'default'|'reverse');setCursor('0');}}><option value="default">Ascending</option><option value="reverse">Descending</option></select></label>
 <button className="button" type="button" disabled={loading} onClick={rerun}>Refresh</button></div>
 <p>Maximum 90 calendar days. Net totals attribute full reversals to the original source date; historical totals may change. These are recorded loyalty sales, with staff-entered bills and eligible spend.</p>
 <a href="#report-definitions">Metric definitions</a>
 <div id="report-panel" {...(!overviewOnly?{role:'tabpanel','aria-labelledby':`tab-${kind}`}:{})} aria-busy={loading}>
 {loading&&<p role="status">Loading {titles[kind].toLowerCase()}…</p>}{error&&<div role="alert" className="notice"><p>{error}</p><button className="button button-secondary" type="button" onClick={rerun}>Retry</button></div>}
 {result&&<><p>Updated {new Date(result.dataAsOf).toLocaleString('en-PK',{timeZone:config.timezone})} · {result.appliedFilters.startDate} to {result.appliedFilters.endDate}</p>
 {kind==='overview'&&result.metrics.recordedPurchases===0&&<p className="notice">No recorded purchases match these filters.</p>}
 <dl className="report-metrics">{Object.entries(result.metrics).map(([key,value])=><div className="screen-panel" key={key}><dt>{metricLabels[key]??label(key)}</dt><dd>{display(value,key)}</dd></div>)}</dl>
 {kind==='overview'&&(result.series??result.rows).some(r=>Number(r.purchases)>0)&&<figure className="screen-panel"><figcaption>Recorded purchases by day · selected interval. Full values are in the table.</figcaption><DailyChart rows={result.series??result.rows}/></figure>}
 {result.rows.length===0?<p className="notice">No activity matches these filters. Try another date range or branch.</p>:<div className="report-table" tabIndex={0} role="region" aria-label={`${titles[kind]} table`}><table><caption>{titles[kind]} · {result.totalRows} rows</caption><thead><tr>{columns[kind].map(k=><th scope="col" key={k}>{label(k)}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{columns[kind].map(k=><td key={k}>{display(row[k],k)}</td>)}</tr>)}</tbody></table></div>}
 <div className="actions"><button className="button button-secondary" type="button" disabled={loading||cursor==='0'} onClick={()=>setCursor(String(Math.max(0,Number(cursor)-pageSize)))}>Previous</button><span>Page {Math.floor(Number(cursor)/pageSize)+1}</span><button className="button button-secondary" type="button" disabled={loading||!result.nextCursor} onClick={()=>setCursor(result.nextCursor!)}>Next</button>
 {config.canExport&&<button className="button" type="button" onClick={()=>beginExport(false)} disabled={exportBusy}>Export CSV</button>}{config.canExportContacts&&kind==='customers'&&<button className="button button-secondary" type="button" onClick={()=>beginExport(true)} disabled={exportBusy}>Export shared contacts</button>}</div></>}
 </div>
 {exportState&&<div className="screen-panel"><h2>Private export</h2><p role="status">{exportState.status==='failed'?(exportState.errorCode==='narrow_filters'?'Export exceeds 10,000 rows or 3 MiB. Narrow filters.':`Export failed: ${exportState.errorCode??'Retry the request.'}`):`Export ${exportState.status}.`}</p>{['pending','processing'].includes(exportState.status)&&<button className="button button-secondary" type="button" onClick={checkExport} disabled={exportBusy}>Check export status</button>}{exportState.status==='completed'&&<><p>{exportState.rowCount} rows · expires {exportState.expiresAt&&new Date(exportState.expiresAt).toLocaleString('en-PK',{timeZone:config.timezone})}. Current permissions are checked on download.</p><a className="button" href={`/api/reports/download?businessId=${businessId}&exportRequestId=${exportState.exportRequestId}`}>Download CSV</a></>}</div>}
 {!confirm&&exportError&&<p role="alert">{exportError}</p>}
 <details id="report-definitions" className="screen-panel"><summary>Metric definitions and limitations</summary><p>Purchasing cards have a non-reversed qualifying purchase. Returning cards had a qualifying purchase on that same card before the selected period. Repeat within period counts cards with two or more qualifying purchases in this period. A customer with two programmes has two cards. A selected reward limits redemption and cost metrics; shared earned units cannot be assigned to an individual reward and show N/A. Average recorded bill uses all non-reversed recorded purchases, including nonqualifying purchases. Zero denominators and unknown merchant reward costs show N/A.</p><p>Earned and redeemed units are net source cohorts; reversal activity is dated when processed. Current outstanding units and adjustment debt are business-wide only when the cafe has one programme. Mixed-programme unit totals show N/A because stamps and points cannot be added meaningfully. Staff activity counts actions at processing time, including original purchases later reversed. Branch views never allocate shared balances.</p><p>Referrals use enrollment cohorts and the qualifying purchase branch, or joined branch while pending. Capped claims can still honor the friend bonus. Approximate visits cover at most 90 days, are not unique people, and branch views use the referrer join branch. Campaign audiences count memberships separately from device attempts; two devices can produce two provider-accepted sends. Acceptance does not prove display or reading. Associated sales do not establish incremental revenue. Manual WhatsApp counts opened tasks and human-attested sent tasks separately.</p><p>Never-purchased and inactive segments use permitted branch history as of the interval end; inactive means no qualifying purchase in the preceding 30 days after having previously purchased. Detailed customer rows represent cards joined by the interval end. CSV quantities ending Paisa remain integer paisa; metadata includes the applied scope and source timestamp. Exports expire after 24 hours.</p></details>
 {confirm&&<dialog ref={dialog} aria-labelledby="export-title" onCancel={()=>{if(!exportBusy)setConfirm(false);}}><h2 id="export-title">{contactExport?'Export shared contacts?':'Export selected report?'}</h2><p>{config.businessName} · {titles[kind]} · {result?.appliedFilters.startDate} to {result?.appliedFilters.endDate} · {branch?config.branches.find(b=>b.id===branch)?.name:config.role==='owner'?'All branches':'All assigned branches'}</p><p>{contactExport?'Contains deliberately shared phone/email. Owner contact exports require verified MFA. Birthdays and consent fields are excluded.':'Phone, email, birthday and consent fields are excluded. Default columns omit customer and staff identity.'} Maximum 10,000 rows / 3 MiB; excessive exports fail with Narrow filters.</p><fieldset><legend>Approved columns</legend>{columns[exportKind].map(c=><label className="report-column" key={c}><input type="checkbox" checked={chosen.includes(c)} onChange={e=>setChosen(old=>e.target.checked?[...old,c]:old.filter(v=>v!==c))}/>{label(c)}</label>)}</fieldset>{exportError&&<p role="alert">{exportError}</p>}<div className="actions"><button className="button button-secondary" type="button" disabled={exportBusy} onClick={()=>{dialog.current?.close();setConfirm(false);}}>Cancel</button><button className="button" type="button" disabled={exportBusy||chosen.length===0} onClick={exportRequest}>{exportBusy?'Requesting…':'Create private export'}</button></div></dialog>}
 </section>;
}
