import {describe,it,expect} from 'vitest';
import {amount,reconciliation,evidence,privacyRequest,adminRead,plan} from '../../src/features/platform/contracts';
import {formPaisa} from '../../src/features/platform/client';
const id='b8000000-0000-4000-8000-000000000001';
describe('financial and privacy boundaries',()=>{
 it('keeps large and fractional PKR exact and rejects imprecise formats',()=>{expect(formPaisa('5.05')).toBe('505');expect(formPaisa('90000000000.00')).toBe('9000000000000');for(const v of ['5.005','1e4','-3','NaN'])expect(()=>formPaisa(v)).toThrow();for(const v of ['0','-1','1.5','9000000000001'])expect(amount.safeParse(v).success).toBe(false);});
 it('requires real reconciliation attestation and full canonical fields',()=>{const input={decision:'confirm',verifiedAmountPaisa:'550050',method:'bank_transfer',provider:'test-bank',reference:'TEST',reconciled:true};expect(reconciliation.safeParse({invoiceId:id,idempotencyKey:id,input}).success).toBe(true);for(const k of ['verifiedAmountPaisa','provider','reference','method','reconciled']){const v={...input} as Record<string,unknown>;delete v[k];expect(reconciliation.safeParse({invoiceId:id,idempotencyKey:id,input:v}).success).toBe(false);}expect(reconciliation.safeParse({invoiceId:id,idempotencyKey:id,input:{decision:'reject',submissionId:id}}).success).toBe(false);});
 it('evidence cannot carry payment status; exports cannot select other accounts',()=>{expect(evidence.safeParse({businessId:id,invoiceId:id,idempotencyKey:id,input:{claimedAmountPaisa:'1',method:'bank_transfer',reference:'TEST',status:'paid'}}).success).toBe(false);expect(privacyRequest.safeParse({kind:'export',membershipId:id,idempotencyKey:id}).success).toBe(false);expect(privacyRequest.safeParse({kind:'export',customerId:id,idempotencyKey:id}).success).toBe(false);expect(privacyRequest.safeParse({kind:'delete_membership',membershipId:id,idempotencyKey:id}).success).toBe(true);});
 it('bounds admin reads and does not add feature flags or zero-price paid plans',()=>{expect(adminRead.safeParse({kind:'audit',filters:{pageSize:101}}).success).toBe(false);expect(adminRead.safeParse({kind:'jobs',filters:{payload:true}}).success).toBe(false);const input={code:'test-plan',name:'TEST plan',active:true,pricePaisa:'1',billingPeriod:'monthly',branchLimit:1,staffLimit:1,memberLimit:null,monthlyCampaignLimit:null,trialDays:14};expect(plan.safeParse({publish:true,input}).success).toBe(true);expect(plan.safeParse({publish:true,input:{...input,pricePaisa:'0'}}).success).toBe(false);expect(plan.safeParse({publish:true,input:{...input,referralsEnabled:false}}).success).toBe(false);});
});
